#pragma once

#include <QString>
#include <QVector>

#include "IconFontStore.h"

namespace Quartz {
struct IconInfo {
    int m_code;
    QString m_font;
    QString m_name;
};

const QVector<IconInfo> ICON_INFO = {
    { 0xE84D, "Material", "Rotation_3d" },
    { 0xEB3B, "Material", "AcUnit" },
    { 0xE190, "Material", "AccessAlarm" },
    { 0xE191, "Material", "AccessAlarms" },
    { 0xE192, "Material", "AccessTime" },
    { 0xE84E, "Material", "Accessibility" },
    { 0xE914, "Material", "Accessible" },
    { 0xE84F, "Material", "AccountBalance" },
    { 0xE850, "Material", "AccountBalanceWallet" },
    { 0xE851, "Material", "AccountBox" },
    { 0xE853, "Material", "AccountCircle" },
    { 0xE60E, "Material", "Adb" },
    { 0xE145, "Material", "Add" },
    { 0xE439, "Material", "AddAPhoto" },
    { 0xE193, "Material", "AddAlarm" },
    { 0xE003, "Material", "AddAlert" },
    { 0xE146, "Material", "AddBox" },
    { 0xE147, "Material", "AddCircle" },
    { 0xE148, "Material", "AddCircleOutline" },
    { 0xE567, "Material", "AddLocation" },
    { 0xE854, "Material", "AddShoppingCart" },
    { 0xE39D, "Material", "AddToPhotos" },
    { 0xE05C, "Material", "AddToQueue" },
    { 0xE39E, "Material", "Adjust" },
    { 0xE630, "Material", "AirlineSeatFlat" },
    { 0xE631, "Material", "AirlineSeatFlatAngled" },
    { 0xE632, "Material", "AirlineSeatIndividualSuite" },
    { 0xE633, "Material", "AirlineSeatLegroomExtra" },
    { 0xE634, "Material", "AirlineSeatLegroomNormal" },
    { 0xE635, "Material", "AirlineSeatLegroomReduced" },
    { 0xE636, "Material", "AirlineSeatReclineExtra" },
    { 0xE637, "Material", "AirlineSeatReclineNormal" },
    { 0xE195, "Material", "AirplanemodeActive" },
    { 0xE194, "Material", "AirplanemodeInactive" },
    { 0xE055, "Material", "Airplay" },
    { 0xEB3C, "Material", "AirportShuttle" },
    { 0xE855, "Material", "Alarm" },
    { 0xE856, "Material", "AlarmAdd" },
    { 0xE857, "Material", "AlarmOff" },
    { 0xE858, "Material", "AlarmOn" },
    { 0xE019, "Material", "Album" },
    { 0xEB3D, "Material", "AllInclusive" },
    { 0xE90B, "Material", "AllOut" },
    { 0xE859, "Material", "Android" },
    { 0xE85A, "Material", "Announcement" },
    { 0xE5C3, "Material", "Apps" },
    { 0xE149, "Material", "Archive" },
    { 0xE5C4, "Material", "ArrowBack" },
    { 0xE5DB, "Material", "ArrowDownward" },
    { 0xE5C5, "Material", "ArrowDropDown" },
    { 0xE5C6, "Material", "ArrowDropDownCircle" },
    { 0xE5C7, "Material", "ArrowDropUp" },
    { 0xE5C8, "Material", "ArrowForward" },
    { 0xE5D8, "Material", "ArrowUpward" },
    { 0xE060, "Material", "ArtTrack" },
    { 0xE85B, "Material", "AspectRatio" },
    { 0xE85C, "Material", "Assessment" },
    { 0xE85D, "Material", "Assignment" },
    { 0xE85E, "Material", "AssignmentInd" },
    { 0xE85F, "Material", "AssignmentLate" },
    { 0xE860, "Material", "AssignmentReturn" },
    { 0xE861, "Material", "AssignmentReturned" },
    { 0xE862, "Material", "AssignmentTurnedIn" },
    { 0xE39F, "Material", "Assistant" },
    { 0xE3A0, "Material", "AssistantPhoto" },
    { 0xE226, "Material", "AttachFile" },
    { 0xE227, "Material", "AttachMoney" },
    { 0xE2BC, "Material", "Attachment" },
    { 0xE3A1, "Material", "Audiotrack" },
    { 0xE863, "Material", "Autorenew" },
    { 0xE01B, "Material", "AvTimer" },
    { 0xE14A, "Material", "Backspace" },
    { 0xE864, "Material", "Backup" },
    { 0xE19C, "Material", "BatteryAlert" },
    { 0xE1A3, "Material", "BatteryChargingFull" },
    { 0xE1A4, "Material", "BatteryFull" },
    { 0xE1A5, "Material", "BatteryStd" },
    { 0xE1A6, "Material", "BatteryUnknown" },
    { 0xEB3E, "Material", "BeachAccess" },
    { 0xE52D, "Material", "Beenhere" },
    { 0xE14B, "Material", "Block" },
    { 0xE1A7, "Material", "Bluetooth" },
    { 0xE60F, "Material", "BluetoothAudio" },
    { 0xE1A8, "Material", "BluetoothConnected" },
    { 0xE1A9, "Material", "BluetoothDisabled" },
    { 0xE1AA, "Material", "BluetoothSearching" },
    { 0xE3A2, "Material", "BlurCircular" },
    { 0xE3A3, "Material", "BlurLinear" },
    { 0xE3A4, "Material", "BlurOff" },
    { 0xE3A5, "Material", "BlurOn" },
    { 0xE865, "Material", "Book" },
    { 0xE866, "Material", "Bookmark" },
    { 0xE867, "Material", "BookmarkBorder" },
    { 0xE228, "Material", "BorderAll" },
    { 0xE229, "Material", "BorderBottom" },
    { 0xE22A, "Material", "BorderClear" },
    { 0xE22B, "Material", "BorderColor" },
    { 0xE22C, "Material", "BorderHorizontal" },
    { 0xE22D, "Material", "BorderInner" },
    { 0xE22E, "Material", "BorderLeft" },
    { 0xE22F, "Material", "BorderOuter" },
    { 0xE230, "Material", "BorderRight" },
    { 0xE231, "Material", "BorderStyle" },
    { 0xE232, "Material", "BorderTop" },
    { 0xE233, "Material", "BorderVertical" },
    { 0xE06B, "Material", "BrandingWatermark" },
    { 0xE3A6, "Material", "Brightness_1" },
    { 0xE3A7, "Material", "Brightness_2" },
    { 0xE3A8, "Material", "Brightness_3" },
    { 0xE3A9, "Material", "Brightness_4" },
    { 0xE3AA, "Material", "Brightness_5" },
    { 0xE3AB, "Material", "Brightness_6" },
    { 0xE3AC, "Material", "Brightness_7" },
    { 0xE1AB, "Material", "BrightnessAuto" },
    { 0xE1AC, "Material", "BrightnessHigh" },
    { 0xE1AD, "Material", "BrightnessLow" },
    { 0xE1AE, "Material", "BrightnessMedium" },
    { 0xE3AD, "Material", "BrokenImage" },
    { 0xE3AE, "Material", "Brush" },
    { 0xE6DD, "Material", "BubbleChart" },
    { 0xE868, "Material", "BugReport" },
    { 0xE869, "Material", "Build" },
    { 0xE43C, "Material", "BurstMode" },
    { 0xE0AF, "Material", "Business" },
    { 0xEB3F, "Material", "BusinessCenter" },
    { 0xE86A, "Material", "Cached" },
    { 0xE7E9, "Material", "Cake" },
    { 0xE0B0, "Material", "Call" },
    { 0xE0B1, "Material", "CallEnd" },
    { 0xE0B2, "Material", "CallMade" },
    { 0xE0B3, "Material", "CallMerge" },
    { 0xE0B4, "Material", "CallMissed" },
    { 0xE0E4, "Material", "CallMissedOutgoing" },
    { 0xE0B5, "Material", "CallReceived" },
    { 0xE0B6, "Material", "CallSplit" },
    { 0xE06C, "Material", "CallToAction" },
    { 0xE3AF, "Material", "Camera" },
    { 0xE3B0, "Material", "CameraAlt" },
    { 0xE8FC, "Material", "CameraEnhance" },
    { 0xE3B1, "Material", "CameraFront" },
    { 0xE3B2, "Material", "CameraRear" },
    { 0xE3B3, "Material", "CameraRoll" },
    { 0xE5C9, "Material", "Cancel" },
    { 0xE8F6, "Material", "CardGiftcard" },
    { 0xE8F7, "Material", "CardMembership" },
    { 0xE8F8, "Material", "CardTravel" },
    { 0xEB40, "Material", "Casino" },
    { 0xE307, "Material", "Cast" },
    { 0xE308, "Material", "CastConnected" },
    { 0xE3B4, "Material", "CenterFocusStrong" },
    { 0xE3B5, "Material", "CenterFocusWeak" },
    { 0xE86B, "Material", "ChangeHistory" },
    { 0xE0B7, "Material", "Chat" },
    { 0xE0CA, "Material", "ChatBubble" },
    { 0xE0CB, "Material", "ChatBubbleOutline" },
    { 0xE5CA, "Material", "Check" },
    { 0xE834, "Material", "CheckBox" },
    { 0xE835, "Material", "CheckBoxOutlineBlank" },
    { 0xE86C, "Material", "CheckCircle" },
    { 0xE5CB, "Material", "ChevronLeft" },
    { 0xE5CC, "Material", "ChevronRight" },
    { 0xEB41, "Material", "ChildCare" },
    { 0xEB42, "Material", "ChildFriendly" },
    { 0xE86D, "Material", "ChromeReaderMode" },
    { 0xE86E, "Material", "Class" },
    { 0xE14C, "Material", "Clear" },
    { 0xE0B8, "Material", "ClearAll" },
    { 0xE5CD, "Material", "Close" },
    { 0xE01C, "Material", "ClosedCaption" },
    { 0xE2BD, "Material", "Cloud" },
    { 0xE2BE, "Material", "CloudCircle" },
    { 0xE2BF, "Material", "CloudDone" },
    { 0xE2C0, "Material", "CloudDownload" },
    { 0xE2C1, "Material", "CloudOff" },
    { 0xE2C2, "Material", "CloudQueue" },
    { 0xE2C3, "Material", "CloudUpload" },
    { 0xE86F, "Material", "Code" },
    { 0xE3B6, "Material", "Collections" },
    { 0xE431, "Material", "CollectionsBookmark" },
    { 0xE3B7, "Material", "ColorLens" },
    { 0xE3B8, "Material", "Colorize" },
    { 0xE0B9, "Material", "Comment" },
    { 0xE3B9, "Material", "Compare" },
    { 0xE915, "Material", "CompareArrows" },
    { 0xE30A, "Material", "Computer" },
    { 0xE638, "Material", "ConfirmationNumber" },
    { 0xE0D0, "Material", "ContactMail" },
    { 0xE0CF, "Material", "ContactPhone" },
    { 0xE0BA, "Material", "Contacts" },
    { 0xE14D, "Material", "ContentCopy" },
    { 0xE14E, "Material", "ContentCut" },
    { 0xE14F, "Material", "ContentPaste" },
    { 0xE3BA, "Material", "ControlPoint" },
    { 0xE3BB, "Material", "ControlPointDuplicate" },
    { 0xE90C, "Material", "Copyright" },
    { 0xE150, "Material", "Create" },
    { 0xE2CC, "Material", "CreateNewFolder" },
    { 0xE870, "Material", "CreditCard" },
    { 0xE3BE, "Material", "Crop" },
    { 0xE3BC, "Material", "Crop_16_9" },
    { 0xE3BD, "Material", "Crop_3_2" },
    { 0xE3BF, "Material", "Crop_5_4" },
    { 0xE3C0, "Material", "Crop_7_5" },
    { 0xE3C1, "Material", "CropDin" },
    { 0xE3C2, "Material", "CropFree" },
    { 0xE3C3, "Material", "CropLandscape" },
    { 0xE3C4, "Material", "CropOriginal" },
    { 0xE3C5, "Material", "CropPortrait" },
    { 0xE437, "Material", "CropRotate" },
    { 0xE3C6, "Material", "CropSquare" },
    { 0xE871, "Material", "Dashboard" },
    { 0xE1AF, "Material", "DataUsage" },
    { 0xE916, "Material", "DateRange" },
    { 0xE3C7, "Material", "Dehaze" },
    { 0xE872, "Material", "Delete" },
    { 0xE92B, "Material", "DeleteForever" },
    { 0xE16C, "Material", "DeleteSweep" },
    { 0xE873, "Material", "Description" },
    { 0xE30B, "Material", "DesktopMac" },
    { 0xE30C, "Material", "DesktopWindows" },
    { 0xE3C8, "Material", "Details" },
    { 0xE30D, "Material", "DeveloperBoard" },
    { 0xE1B0, "Material", "DeveloperMode" },
    { 0xE335, "Material", "DeviceHub" },
    { 0xE1B1, "Material", "Devices" },
    { 0xE337, "Material", "DevicesOther" },
    { 0xE0BB, "Material", "DialerSip" },
    { 0xE0BC, "Material", "Dialpad" },
    { 0xE52E, "Material", "Directions" },
    { 0xE52F, "Material", "DirectionsBike" },
    { 0xE532, "Material", "DirectionsBoat" },
    { 0xE530, "Material", "DirectionsBus" },
    { 0xE531, "Material", "DirectionsCar" },
    { 0xE534, "Material", "DirectionsRailway" },
    { 0xE566, "Material", "DirectionsRun" },
    { 0xE533, "Material", "DirectionsSubway" },
    { 0xE535, "Material", "DirectionsTransit" },
    { 0xE536, "Material", "DirectionsWalk" },
    { 0xE610, "Material", "DiscFull" },
    { 0xE875, "Material", "Dns" },
    { 0xE612, "Material", "DoNotDisturb" },
    { 0xE611, "Material", "DoNotDisturbAlt" },
    { 0xE643, "Material", "DoNotDisturbOff" },
    { 0xE644, "Material", "DoNotDisturbOn" },
    { 0xE30E, "Material", "Dock" },
    { 0xE7EE, "Material", "Domain" },
    { 0xE876, "Material", "Done" },
    { 0xE877, "Material", "DoneAll" },
    { 0xE917, "Material", "DonutLarge" },
    { 0xE918, "Material", "DonutSmall" },
    { 0xE151, "Material", "Drafts" },
    { 0xE25D, "Material", "DragHandle" },
    { 0xE613, "Material", "DriveEta" },
    { 0xE1B2, "Material", "Dvr" },
    { 0xE3C9, "Material", "Edit" },
    { 0xE568, "Material", "EditLocation" },
    { 0xE8FB, "Material", "Eject" },
    { 0xE0BE, "Material", "Email" },
    { 0xE63F, "Material", "EnhancedEncryption" },
    { 0xE01D, "Material", "Equalizer" },
    { 0xE000, "Material", "Error" },
    { 0xE001, "Material", "ErrorOutline" },
    { 0xE926, "Material", "EuroSymbol" },
    { 0xE56D, "Material", "EvStation" },
    { 0xE878, "Material", "Event" },
    { 0xE614, "Material", "EventAvailable" },
    { 0xE615, "Material", "EventBusy" },
    { 0xE616, "Material", "EventNote" },
    { 0xE903, "Material", "EventSeat" },
    { 0xE879, "Material", "ExitToApp" },
    { 0xE5CE, "Material", "ExpandLess" },
    { 0xE5CF, "Material", "ExpandMore" },
    { 0xE01E, "Material", "Explicit" },
    { 0xE87A, "Material", "Explore" },
    { 0xE3CA, "Material", "Exposure" },
    { 0xE3CB, "Material", "ExposureNeg_1" },
    { 0xE3CC, "Material", "ExposureNeg_2" },
    { 0xE3CD, "Material", "ExposurePlus_1" },
    { 0xE3CE, "Material", "ExposurePlus_2" },
    { 0xE3CF, "Material", "ExposureZero" },
    { 0xE87B, "Material", "Extension" },
    { 0xE87C, "Material", "Face" },
    { 0xE01F, "Material", "FastForward" },
    { 0xE020, "Material", "FastRewind" },
    { 0xE87D, "Material", "Favorite" },
    { 0xE87E, "Material", "FavoriteBorder" },
    { 0xE06D, "Material", "FeaturedPlayList" },
    { 0xE06E, "Material", "FeaturedVideo" },
    { 0xE87F, "Material", "Feedback" },
    { 0xE05D, "Material", "FiberDvr" },
    { 0xE061, "Material", "FiberManualRecord" },
    { 0xE05E, "Material", "FiberNew" },
    { 0xE06A, "Material", "FiberPin" },
    { 0xE062, "Material", "FiberSmartRecord" },
    { 0xE2C4, "Material", "FileDownload" },
    { 0xE2C6, "Material", "FileUpload" },
    { 0xE3D3, "Material", "Filter" },
    { 0xE3D0, "Material", "Filter_1" },
    { 0xE3D1, "Material", "Filter_2" },
    { 0xE3D2, "Material", "Filter_3" },
    { 0xE3D4, "Material", "Filter_4" },
    { 0xE3D5, "Material", "Filter_5" },
    { 0xE3D6, "Material", "Filter_6" },
    { 0xE3D7, "Material", "Filter_7" },
    { 0xE3D8, "Material", "Filter_8" },
    { 0xE3D9, "Material", "Filter_9" },
    { 0xE3DA, "Material", "Filter_9Plus" },
    { 0xE3DB, "Material", "FilterBAndW" },
    { 0xE3DC, "Material", "FilterCenterFocus" },
    { 0xE3DD, "Material", "FilterDrama" },
    { 0xE3DE, "Material", "FilterFrames" },
    { 0xE3DF, "Material", "FilterHdr" },
    { 0xE152, "Material", "FilterList" },
    { 0xE3E0, "Material", "FilterNone" },
    { 0xE3E2, "Material", "FilterTiltShift" },
    { 0xE3E3, "Material", "FilterVintage" },
    { 0xE880, "Material", "FindInPage" },
    { 0xE881, "Material", "FindReplace" },
    { 0xE90D, "Material", "Fingerprint" },
    { 0xE5DC, "Material", "FirstPage" },
    { 0xEB43, "Material", "FitnessCenter" },
    { 0xE153, "Material", "Flag" },
    { 0xE3E4, "Material", "Flare" },
    { 0xE3E5, "Material", "FlashAuto" },
    { 0xE3E6, "Material", "FlashOff" },
    { 0xE3E7, "Material", "FlashOn" },
    { 0xE539, "Material", "Flight" },
    { 0xE904, "Material", "FlightLand" },
    { 0xE905, "Material", "FlightTakeoff" },
    { 0xE3E8, "Material", "Flip" },
    { 0xE882, "Material", "FlipToBack" },
    { 0xE883, "Material", "FlipToFront" },
    { 0xE2C7, "Material", "Folder" },
    { 0xE2C8, "Material", "FolderOpen" },
    { 0xE2C9, "Material", "FolderShared" },
    { 0xE617, "Material", "FolderSpecial" },
    { 0xE167, "Material", "FontDownload" },
    { 0xE234, "Material", "FormatAlignCenter" },
    { 0xE235, "Material", "FormatAlignJustify" },
    { 0xE236, "Material", "FormatAlignLeft" },
    { 0xE237, "Material", "FormatAlignRight" },
    { 0xE238, "Material", "FormatBold" },
    { 0xE239, "Material", "FormatClear" },
    { 0xE23A, "Material", "FormatColorFill" },
    { 0xE23B, "Material", "FormatColorReset" },
    { 0xE23C, "Material", "FormatColorText" },
    { 0xE23D, "Material", "FormatIndentDecrease" },
    { 0xE23E, "Material", "FormatIndentIncrease" },
    { 0xE23F, "Material", "FormatItalic" },
    { 0xE240, "Material", "FormatLineSpacing" },
    { 0xE241, "Material", "FormatListBulleted" },
    { 0xE242, "Material", "FormatListNumbered" },
    { 0xE243, "Material", "FormatPaint" },
    { 0xE244, "Material", "FormatQuote" },
    { 0xE25E, "Material", "FormatShapes" },
    { 0xE245, "Material", "FormatSize" },
    { 0xE246, "Material", "FormatStrikethrough" },
    { 0xe247, "Material", "FormatTextdirectionLToR" },
    { 0xe248, "Material", "FormatTextdirectionRToL" },
    { 0xE249, "Material", "FormatUnderlined" },
    { 0xE0BF, "Material", "Forum" },
    { 0xE154, "Material", "Forward" },
    { 0xE056, "Material", "Forward_10" },
    { 0xE057, "Material", "Forward_30" },
    { 0xE058, "Material", "Forward_5" },
    { 0xEB44, "Material", "FreeBreakfast" },
    { 0xE5D0, "Material", "Fullscreen" },
    { 0xE5D1, "Material", "FullscreenExit" },
    { 0xE24A, "Material", "Functions" },
    { 0xE927, "Material", "GTranslate" },
    { 0xE30F, "Material", "Gamepad" },
    { 0xE021, "Material", "Games" },
    { 0xE90E, "Material", "Gavel" },
    { 0xE155, "Material", "Gesture" },
    { 0xE884, "Material", "GetApp" },
    { 0xE908, "Material", "Gif" },
    { 0xEB45, "Material", "GolfCourse" },
    { 0xE1B3, "Material", "GpsFixed" },
    { 0xE1B4, "Material", "GpsNotFixed" },
    { 0xE1B5, "Material", "GpsOff" },
    { 0xE885, "Material", "Grade" },
    { 0xE3E9, "Material", "Gradient" },
    { 0xE3EA, "Material", "Grain" },
    { 0xE1B8, "Material", "GraphicEq" },
    { 0xE3EB, "Material", "GridOff" },
    { 0xE3EC, "Material", "GridOn" },
    { 0xE7EF, "Material", "Group" },
    { 0xE7F0, "Material", "GroupAdd" },
    { 0xE886, "Material", "GroupWork" },
    { 0xE052, "Material", "Hd" },
    { 0xE3ED, "Material", "HdrOff" },
    { 0xE3EE, "Material", "HdrOn" },
    { 0xE3F1, "Material", "HdrStrong" },
    { 0xE3F2, "Material", "HdrWeak" },
    { 0xE310, "Material", "Headset" },
    { 0xE311, "Material", "HeadsetMic" },
    { 0xE3F3, "Material", "Healing" },
    { 0xE023, "Material", "Hearing" },
    { 0xE887, "Material", "Help" },
    { 0xE8FD, "Material", "HelpOutline" },
    { 0xE024, "Material", "HighQuality" },
    { 0xE25F, "Material", "Highlight" },
    { 0xE888, "Material", "HighlightOff" },
    { 0xE889, "Material", "History" },
    { 0xE88A, "Material", "Home" },
    { 0xEB46, "Material", "HotTub" },
    { 0xE53A, "Material", "Hotel" },
    { 0xE88B, "Material", "HourglassEmpty" },
    { 0xE88C, "Material", "HourglassFull" },
    { 0xE902, "Material", "Http" },
    { 0xE88D, "Material", "Https" },
    { 0xE3F4, "Material", "Image" },
    { 0xE3F5, "Material", "ImageAspectRatio" },
    { 0xE0E0, "Material", "ImportContacts" },
    { 0xE0C3, "Material", "ImportExport" },
    { 0xE912, "Material", "ImportantDevices" },
    { 0xE156, "Material", "Inbox" },
    { 0xE909, "Material", "IndeterminateCheckBox" },
    { 0xE88E, "Material", "Info" },
    { 0xE88F, "Material", "InfoOutline" },
    { 0xE890, "Material", "Input" },
    { 0xE24B, "Material", "InsertChart" },
    { 0xE24C, "Material", "InsertComment" },
    { 0xE24D, "Material", "InsertDriveFile" },
    { 0xE24E, "Material", "InsertEmoticon" },
    { 0xE24F, "Material", "InsertInvitation" },
    { 0xE250, "Material", "InsertLink" },
    { 0xE251, "Material", "InsertPhoto" },
    { 0xE891, "Material", "InvertColors" },
    { 0xE0C4, "Material", "InvertColorsOff" },
    { 0xE3F6, "Material", "Iso" },
    { 0xE312, "Material", "Keyboard" },
    { 0xE313, "Material", "KeyboardArrowDown" },
    { 0xE314, "Material", "KeyboardArrowLeft" },
    { 0xE315, "Material", "KeyboardArrowRight" },
    { 0xE316, "Material", "KeyboardArrowUp" },
    { 0xE317, "Material", "KeyboardBackspace" },
    { 0xE318, "Material", "KeyboardCapslock" },
    { 0xE31A, "Material", "KeyboardHide" },
    { 0xE31B, "Material", "KeyboardReturn" },
    { 0xE31C, "Material", "KeyboardTab" },
    { 0xE31D, "Material", "KeyboardVoice" },
    { 0xEB47, "Material", "Kitchen" },
    { 0xE892, "Material", "Label" },
    { 0xE893, "Material", "LabelOutline" },
    { 0xE3F7, "Material", "Landscape" },
    { 0xE894, "Material", "Language" },
    { 0xE31E, "Material", "Laptop" },
    { 0xE31F, "Material", "LaptopChromebook" },
    { 0xE320, "Material", "LaptopMac" },
    { 0xE321, "Material", "LaptopWindows" },
    { 0xE5DD, "Material", "LastPage" },
    { 0xE895, "Material", "Launch" },
    { 0xE53B, "Material", "Layers" },
    { 0xE53C, "Material", "LayersClear" },
    { 0xE3F8, "Material", "LeakAdd" },
    { 0xE3F9, "Material", "LeakRemove" },
    { 0xE3FA, "Material", "Lens" },
    { 0xE02E, "Material", "LibraryAdd" },
    { 0xE02F, "Material", "LibraryBooks" },
    { 0xE030, "Material", "LibraryMusic" },
    { 0xE90F, "Material", "LightbulbOutline" },
    { 0xE919, "Material", "LineStyle" },
    { 0xE91A, "Material", "LineWeight" },
    { 0xE260, "Material", "LinearScale" },
    { 0xE157, "Material", "Link" },
    { 0xE438, "Material", "LinkedCamera" },
    { 0xE896, "Material", "List" },
    { 0xE0C6, "Material", "LiveHelp" },
    { 0xE639, "Material", "LiveTv" },
    { 0xE53F, "Material", "LocalActivity" },
    { 0xE53D, "Material", "LocalAirport" },
    { 0xE53E, "Material", "LocalAtm" },
    { 0xE540, "Material", "LocalBar" },
    { 0xE541, "Material", "LocalCafe" },
    { 0xE542, "Material", "LocalCarWash" },
    { 0xE543, "Material", "LocalConvenienceStore" },
    { 0xE556, "Material", "LocalDining" },
    { 0xE544, "Material", "LocalDrink" },
    { 0xE545, "Material", "LocalFlorist" },
    { 0xE546, "Material", "LocalGasStation" },
    { 0xE547, "Material", "LocalGroceryStore" },
    { 0xE548, "Material", "LocalHospital" },
    { 0xE549, "Material", "LocalHotel" },
    { 0xE54A, "Material", "LocalLaundryService" },
    { 0xE54B, "Material", "LocalLibrary" },
    { 0xE54C, "Material", "LocalMall" },
    { 0xE54D, "Material", "LocalMovies" },
    { 0xE54E, "Material", "LocalOffer" },
    { 0xE54F, "Material", "LocalParking" },
    { 0xE550, "Material", "LocalPharmacy" },
    { 0xE551, "Material", "LocalPhone" },
    { 0xE552, "Material", "LocalPizza" },
    { 0xE553, "Material", "LocalPlay" },
    { 0xE554, "Material", "LocalPostOffice" },
    { 0xE555, "Material", "LocalPrintshop" },
    { 0xE557, "Material", "LocalSee" },
    { 0xE558, "Material", "LocalShipping" },
    { 0xE559, "Material", "LocalTaxi" },
    { 0xE7F1, "Material", "LocationCity" },
    { 0xE1B6, "Material", "LocationDisabled" },
    { 0xE0C7, "Material", "LocationOff" },
    { 0xE0C8, "Material", "LocationOn" },
    { 0xE1B7, "Material", "LocationSearching" },
    { 0xE897, "Material", "Lock" },
    { 0xE898, "Material", "LockOpen" },
    { 0xE899, "Material", "LockOutline" },
    { 0xE3FC, "Material", "Looks" },
    { 0xE3FB, "Material", "Looks_3" },
    { 0xE3FD, "Material", "Looks_4" },
    { 0xE3FE, "Material", "Looks_5" },
    { 0xE3FF, "Material", "Looks_6" },
    { 0xE400, "Material", "LooksOne" },
    { 0xE401, "Material", "LooksTwo" },
    { 0xE028, "Material", "Loop" },
    { 0xE402, "Material", "Loupe" },
    { 0xE16D, "Material", "LowPriority" },
    { 0xE89A, "Material", "Loyalty" },
    { 0xE158, "Material", "Mail" },
    { 0xE0E1, "Material", "MailOutline" },
    { 0xE55B, "Material", "Map" },
    { 0xE159, "Material", "Markunread" },
    { 0xE89B, "Material", "MarkunreadMailbox" },
    { 0xE322, "Material", "Memory" },
    { 0xE5D2, "Material", "Menu" },
    { 0xE252, "Material", "MergeType" },
    { 0xE0C9, "Material", "Message" },
    { 0xE029, "Material", "Mic" },
    { 0xE02A, "Material", "MicNone" },
    { 0xE02B, "Material", "MicOff" },
    { 0xE618, "Material", "Mms" },
    { 0xE253, "Material", "ModeComment" },
    { 0xE254, "Material", "ModeEdit" },
    { 0xE263, "Material", "MonetizationOn" },
    { 0xE25C, "Material", "MoneyOff" },
    { 0xE403, "Material", "MonochromePhotos" },
    { 0xE7F2, "Material", "Mood" },
    { 0xE7F3, "Material", "MoodBad" },
    { 0xE619, "Material", "More" },
    { 0xE5D3, "Material", "MoreHoriz" },
    { 0xE5D4, "Material", "MoreVert" },
    { 0xE91B, "Material", "Motorcycle" },
    { 0xE323, "Material", "Mouse" },
    { 0xE168, "Material", "MoveToInbox" },
    { 0xE02C, "Material", "Movie" },
    { 0xE404, "Material", "MovieCreation" },
    { 0xE43A, "Material", "MovieFilter" },
    { 0xE6DF, "Material", "MultilineChart" },
    { 0xE405, "Material", "MusicNote" },
    { 0xE063, "Material", "MusicVideo" },
    { 0xE55C, "Material", "MyLocation" },
    { 0xE406, "Material", "Nature" },
    { 0xE407, "Material", "NaturePeople" },
    { 0xE408, "Material", "NavigateBefore" },
    { 0xE409, "Material", "NavigateNext" },
    { 0xE55D, "Material", "Navigation" },
    { 0xE569, "Material", "NearMe" },
    { 0xE1B9, "Material", "NetworkCell" },
    { 0xE640, "Material", "NetworkCheck" },
    { 0xE61A, "Material", "NetworkLocked" },
    { 0xE1BA, "Material", "NetworkWifi" },
    { 0xE031, "Material", "NewReleases" },
    { 0xE16A, "Material", "NextWeek" },
    { 0xE1BB, "Material", "Nfc" },
    { 0xE641, "Material", "NoEncryption" },
    { 0xE0CC, "Material", "NoSim" },
    { 0xE033, "Material", "NotInterested" },
    { 0xE06F, "Material", "Note" },
    { 0xE89C, "Material", "NoteAdd" },
    { 0xE7F4, "Material", "Notifications" },
    { 0xE7F7, "Material", "NotificationsActive" },
    { 0xE7F5, "Material", "NotificationsNone" },
    { 0xE7F6, "Material", "NotificationsOff" },
    { 0xE7F8, "Material", "NotificationsPaused" },
    { 0xE90A, "Material", "OfflinePin" },
    { 0xE63A, "Material", "OndemandVideo" },
    { 0xE91C, "Material", "Opacity" },
    { 0xE89D, "Material", "OpenInBrowser" },
    { 0xE89E, "Material", "OpenInNew" },
    { 0xE89F, "Material", "OpenWith" },
    { 0xE7F9, "Material", "Pages" },
    { 0xE8A0, "Material", "Pageview" },
    { 0xE40A, "Material", "Palette" },
    { 0xE925, "Material", "PanTool" },
    { 0xE40B, "Material", "Panorama" },
    { 0xE40C, "Material", "PanoramaFishEye" },
    { 0xE40D, "Material", "PanoramaHorizontal" },
    { 0xE40E, "Material", "PanoramaVertical" },
    { 0xE40F, "Material", "PanoramaWideAngle" },
    { 0xE7FA, "Material", "PartyMode" },
    { 0xE034, "Material", "Pause" },
    { 0xE035, "Material", "PauseCircleFilled" },
    { 0xE036, "Material", "PauseCircleOutline" },
    { 0xE8A1, "Material", "Payment" },
    { 0xE7FB, "Material", "People" },
    { 0xE7FC, "Material", "PeopleOutline" },
    { 0xE8A2, "Material", "PermCameraMic" },
    { 0xE8A3, "Material", "PermContactCalendar" },
    { 0xE8A4, "Material", "PermDataSetting" },
    { 0xE8A5, "Material", "PermDeviceInformation" },
    { 0xE8A6, "Material", "PermIdentity" },
    { 0xE8A7, "Material", "PermMedia" },
    { 0xE8A8, "Material", "PermPhoneMsg" },
    { 0xE8A9, "Material", "PermScanWifi" },
    { 0xE7FD, "Material", "Person" },
    { 0xE7FE, "Material", "PersonAdd" },
    { 0xE7FF, "Material", "PersonOutline" },
    { 0xE55A, "Material", "PersonPin" },
    { 0xE56A, "Material", "PersonPinCircle" },
    { 0xE63B, "Material", "PersonalVideo" },
    { 0xE91D, "Material", "Pets" },
    { 0xE0CD, "Material", "Phone" },
    { 0xE324, "Material", "PhoneAndroid" },
    { 0xE61B, "Material", "PhoneBluetoothSpeaker" },
    { 0xE61C, "Material", "PhoneForwarded" },
    { 0xE61D, "Material", "PhoneInTalk" },
    { 0xE325, "Material", "PhoneIphone" },
    { 0xE61E, "Material", "PhoneLocked" },
    { 0xE61F, "Material", "PhoneMissed" },
    { 0xE620, "Material", "PhonePaused" },
    { 0xE326, "Material", "Phonelink" },
    { 0xE0DB, "Material", "PhonelinkErase" },
    { 0xE0DC, "Material", "PhonelinkLock" },
    { 0xE327, "Material", "PhonelinkOff" },
    { 0xE0DD, "Material", "PhonelinkRing" },
    { 0xE0DE, "Material", "PhonelinkSetup" },
    { 0xE410, "Material", "Photo" },
    { 0xE411, "Material", "PhotoAlbum" },
    { 0xE412, "Material", "PhotoCamera" },
    { 0xE43B, "Material", "PhotoFilter" },
    { 0xE413, "Material", "PhotoLibrary" },
    { 0xE432, "Material", "PhotoSizeSelectActual" },
    { 0xE433, "Material", "PhotoSizeSelectLarge" },
    { 0xE434, "Material", "PhotoSizeSelectSmall" },
    { 0xE415, "Material", "PictureAsPdf" },
    { 0xE8AA, "Material", "PictureInPicture" },
    { 0xE911, "Material", "PictureInPictureAlt" },
    { 0xE6C4, "Material", "PieChart" },
    { 0xE6C5, "Material", "PieChartOutlined" },
    { 0xE55E, "Material", "PinDrop" },
    { 0xE55F, "Material", "Place" },
    { 0xE037, "Material", "PlayArrow" },
    { 0xE038, "Material", "PlayCircleFilled" },
    { 0xE039, "Material", "PlayCircleOutline" },
    { 0xE906, "Material", "PlayForWork" },
    { 0xE03B, "Material", "PlaylistAdd" },
    { 0xE065, "Material", "PlaylistAddCheck" },
    { 0xE05F, "Material", "PlaylistPlay" },
    { 0xE800, "Material", "PlusOne" },
    { 0xE801, "Material", "Poll" },
    { 0xE8AB, "Material", "Polymer" },
    { 0xEB48, "Material", "Pool" },
    { 0xE0CE, "Material", "PortableWifiOff" },
    { 0xE416, "Material", "Portrait" },
    { 0xE63C, "Material", "Power" },
    { 0xE336, "Material", "PowerInput" },
    { 0xE8AC, "Material", "PowerSettingsNew" },
    { 0xE91E, "Material", "PregnantWoman" },
    { 0xE0DF, "Material", "PresentToAll" },
    { 0xE8AD, "Material", "Print" },
    { 0xE645, "Material", "PriorityHigh" },
    { 0xE80B, "Material", "Public" },
    { 0xE255, "Material", "Publish" },
    { 0xE8AE, "Material", "QueryBuilder" },
    { 0xE8AF, "Material", "QuestionAnswer" },
    { 0xE03C, "Material", "Queue" },
    { 0xE03D, "Material", "QueueMusic" },
    { 0xE066, "Material", "QueuePlayNext" },
    { 0xE03E, "Material", "Radio" },
    { 0xE837, "Material", "RadioButtonChecked" },
    { 0xE836, "Material", "RadioButtonUnchecked" },
    { 0xE560, "Material", "RateReview" },
    { 0xE8B0, "Material", "Receipt" },
    { 0xE03F, "Material", "RecentActors" },
    { 0xE91F, "Material", "RecordVoiceOver" },
    { 0xE8B1, "Material", "Redeem" },
    { 0xE15A, "Material", "Redo" },
    { 0xE5D5, "Material", "Refresh" },
    { 0xE15B, "Material", "Remove" },
    { 0xE15C, "Material", "RemoveCircle" },
    { 0xE15D, "Material", "RemoveCircleOutline" },
    { 0xE067, "Material", "RemoveFromQueue" },
    { 0xE417, "Material", "RemoveRedEye" },
    { 0xE928, "Material", "RemoveShoppingCart" },
    { 0xE8FE, "Material", "Reorder" },
    { 0xE040, "Material", "Repeat" },
    { 0xE041, "Material", "RepeatOne" },
    { 0xE042, "Material", "Replay" },
    { 0xE059, "Material", "Replay_10" },
    { 0xE05A, "Material", "Replay_30" },
    { 0xE05B, "Material", "Replay_5" },
    { 0xE15E, "Material", "Reply" },
    { 0xE15F, "Material", "ReplyAll" },
    { 0xE160, "Material", "Report" },
    { 0xE8B2, "Material", "ReportProblem" },
    { 0xE56C, "Material", "Restaurant" },
    { 0xE561, "Material", "RestaurantMenu" },
    { 0xE8B3, "Material", "Restore" },
    { 0xE929, "Material", "RestorePage" },
    { 0xE0D1, "Material", "RingVolume" },
    { 0xE8B4, "Material", "Room" },
    { 0xEB49, "Material", "RoomService" },
    { 0xE418, "Material", "Rotate_90DegreesCcw" },
    { 0xE419, "Material", "RotateLeft" },
    { 0xE41A, "Material", "RotateRight" },
    { 0xE920, "Material", "RoundedCorner" },
    { 0xE328, "Material", "Router" },
    { 0xE921, "Material", "Rowing" },
    { 0xE0E5, "Material", "RssFeed" },
    { 0xE642, "Material", "RvHookup" },
    { 0xE562, "Material", "Satellite" },
    { 0xE161, "Material", "Save" },
    { 0xE329, "Material", "Scanner" },
    { 0xE8B5, "Material", "Schedule" },
    { 0xE80C, "Material", "School" },
    { 0xE1BE, "Material", "ScreenLockLandscape" },
    { 0xE1BF, "Material", "ScreenLockPortrait" },
    { 0xE1C0, "Material", "ScreenLockRotation" },
    { 0xE1C1, "Material", "ScreenRotation" },
    { 0xE0E2, "Material", "ScreenShare" },
    { 0xE623, "Material", "SdCard" },
    { 0xE1C2, "Material", "SdStorage" },
    { 0xE8B6, "Material", "Search" },
    { 0xE32A, "Material", "Security" },
    { 0xE162, "Material", "SelectAll" },
    { 0xE163, "Material", "Send" },
    { 0xE811, "Material", "SentimentDissatisfied" },
    { 0xE812, "Material", "SentimentNeutral" },
    { 0xE813, "Material", "SentimentSatisfied" },
    { 0xE814, "Material", "SentimentVeryDissatisfied" },
    { 0xE815, "Material", "SentimentVerySatisfied" },
    { 0xE8B8, "Material", "Settings" },
    { 0xE8B9, "Material", "SettingsApplications" },
    { 0xE8BA, "Material", "SettingsBackupRestore" },
    { 0xE8BB, "Material", "SettingsBluetooth" },
    { 0xE8BD, "Material", "SettingsBrightness" },
    { 0xE8BC, "Material", "SettingsCell" },
    { 0xE8BE, "Material", "SettingsEthernet" },
    { 0xE8BF, "Material", "SettingsInputAntenna" },
    { 0xE8C0, "Material", "SettingsInputComponent" },
    { 0xE8C1, "Material", "SettingsInputComposite" },
    { 0xE8C2, "Material", "SettingsInputHdmi" },
    { 0xE8C3, "Material", "SettingsInputSvideo" },
    { 0xE8C4, "Material", "SettingsOverscan" },
    { 0xE8C5, "Material", "SettingsPhone" },
    { 0xE8C6, "Material", "SettingsPower" },
    { 0xE8C7, "Material", "SettingsRemote" },
    { 0xE1C3, "Material", "SettingsSystemDaydream" },
    { 0xE8C8, "Material", "SettingsVoice" },
    { 0xE80D, "Material", "Share" },
    { 0xE8C9, "Material", "Shop" },
    { 0xE8CA, "Material", "ShopTwo" },
    { 0xE8CB, "Material", "ShoppingBasket" },
    { 0xE8CC, "Material", "ShoppingCart" },
    { 0xE261, "Material", "ShortText" },
    { 0xE6E1, "Material", "ShowChart" },
    { 0xE043, "Material", "Shuffle" },
    { 0xE1C8, "Material", "SignalCellular_4Bar" },
    { 0xE1CD, "Material", "SignalCellularConnectedNoInternet" },
    { 0xE1CE, "Material", "SignalCellularNoSim" },
    { 0xE1CF, "Material", "SignalCellularNull" },
    { 0xE1D0, "Material", "SignalCellularOff" },
    { 0xE1D8, "Material", "SignalWifi_4Bar" },
    { 0xE1D9, "Material", "SignalWifi_4BarLock" },
    { 0xE1DA, "Material", "SignalWifiOff" },
    { 0xE32B, "Material", "SimCard" },
    { 0xE624, "Material", "SimCardAlert" },
    { 0xE044, "Material", "SkipNext" },
    { 0xE045, "Material", "SkipPrevious" },
    { 0xE41B, "Material", "Slideshow" },
    { 0xE068, "Material", "SlowMotionVideo" },
    { 0xE32C, "Material", "Smartphone" },
    { 0xEB4A, "Material", "SmokeFree" },
    { 0xEB4B, "Material", "SmokingRooms" },
    { 0xE625, "Material", "Sms" },
    { 0xE626, "Material", "SmsFailed" },
    { 0xE046, "Material", "Snooze" },
    { 0xE164, "Material", "Sort" },
    { 0xE053, "Material", "SortByAlpha" },
    { 0xEB4C, "Material", "Spa" },
    { 0xE256, "Material", "SpaceBar" },
    { 0xE32D, "Material", "Speaker" },
    { 0xE32E, "Material", "SpeakerGroup" },
    { 0xE8CD, "Material", "SpeakerNotes" },
    { 0xE92A, "Material", "SpeakerNotesOff" },
    { 0xE0D2, "Material", "SpeakerPhone" },
    { 0xE8CE, "Material", "Spellcheck" },
    { 0xE838, "Material", "Star" },
    { 0xE83A, "Material", "StarBorder" },
    { 0xE839, "Material", "StarHalf" },
    { 0xE8D0, "Material", "Stars" },
    { 0xE0D3, "Material", "StayCurrentLandscape" },
    { 0xE0D4, "Material", "StayCurrentPortrait" },
    { 0xE0D5, "Material", "StayPrimaryLandscape" },
    { 0xE0D6, "Material", "StayPrimaryPortrait" },
    { 0xE047, "Material", "Stop" },
    { 0xE0E3, "Material", "StopScreenShare" },
    { 0xE1DB, "Material", "Storage" },
    { 0xE8D1, "Material", "Store" },
    { 0xE563, "Material", "StoreMallDirectory" },
    { 0xE41C, "Material", "Straighten" },
    { 0xE56E, "Material", "Streetview" },
    { 0xE257, "Material", "StrikethroughS" },
    { 0xE41D, "Material", "Style" },
    { 0xE5D9, "Material", "SubdirectoryArrowLeft" },
    { 0xE5DA, "Material", "SubdirectoryArrowRight" },
    { 0xE8D2, "Material", "Subject" },
    { 0xE064, "Material", "Subscriptions" },
    { 0xE048, "Material", "Subtitles" },
    { 0xE56F, "Material", "Subway" },
    { 0xE8D3, "Material", "SupervisorAccount" },
    { 0xE049, "Material", "SurroundSound" },
    { 0xE0D7, "Material", "SwapCalls" },
    { 0xE8D4, "Material", "SwapHoriz" },
    { 0xE8D5, "Material", "SwapVert" },
    { 0xE8D6, "Material", "SwapVerticalCircle" },
    { 0xE41E, "Material", "SwitchCamera" },
    { 0xE41F, "Material", "SwitchVideo" },
    { 0xE627, "Material", "Sync" },
    { 0xE628, "Material", "SyncDisabled" },
    { 0xE629, "Material", "SyncProblem" },
    { 0xE62A, "Material", "SystemUpdate" },
    { 0xE8D7, "Material", "SystemUpdateAlt" },
    { 0xE8D8, "Material", "Tab" },
    { 0xE8D9, "Material", "TabUnselected" },
    { 0xE32F, "Material", "Tablet" },
    { 0xE330, "Material", "TabletAndroid" },
    { 0xE331, "Material", "TabletMac" },
    { 0xE420, "Material", "TagFaces" },
    { 0xE62B, "Material", "TapAndPlay" },
    { 0xE564, "Material", "Terrain" },
    { 0xE262, "Material", "TextFields" },
    { 0xE165, "Material", "TextFormat" },
    { 0xE0D8, "Material", "Textsms" },
    { 0xE421, "Material", "Texture" },
    { 0xE8DA, "Material", "Theaters" },
    { 0xE8DB, "Material", "ThumbDown" },
    { 0xE8DC, "Material", "ThumbUp" },
    { 0xE8DD, "Material", "ThumbsUpDown" },
    { 0xE62C, "Material", "TimeToLeave" },
    { 0xE422, "Material", "Timelapse" },
    { 0xE922, "Material", "Timeline" },
    { 0xE425, "Material", "Timer" },
    { 0xE423, "Material", "Timer_10" },
    { 0xE424, "Material", "Timer_3" },
    { 0xE426, "Material", "TimerOff" },
    { 0xE264, "Material", "Title" },
    { 0xE8DE, "Material", "Toc" },
    { 0xE8DF, "Material", "Today" },
    { 0xE8E0, "Material", "Toll" },
    { 0xE427, "Material", "Tonality" },
    { 0xE913, "Material", "TouchApp" },
    { 0xE332, "Material", "Toys" },
    { 0xE8E1, "Material", "TrackChanges" },
    { 0xE565, "Material", "Traffic" },
    { 0xE570, "Material", "Train" },
    { 0xE571, "Material", "Tram" },
    { 0xE572, "Material", "TransferWithinAStation" },
    { 0xE428, "Material", "Transform" },
    { 0xE8E2, "Material", "Translate" },
    { 0xE8E3, "Material", "TrendingDown" },
    { 0xE8E4, "Material", "TrendingFlat" },
    { 0xE8E5, "Material", "TrendingUp" },
    { 0xE429, "Material", "Tune" },
    { 0xE8E6, "Material", "TurnedIn" },
    { 0xE8E7, "Material", "TurnedInNot" },
    { 0xE333, "Material", "Tv" },
    { 0xE169, "Material", "Unarchive" },
    { 0xE166, "Material", "Undo" },
    { 0xE5D6, "Material", "UnfoldLess" },
    { 0xE5D7, "Material", "UnfoldMore" },
    { 0xE923, "Material", "Update" },
    { 0xE1E0, "Material", "Usb" },
    { 0xE8E8, "Material", "VerifiedUser" },
    { 0xE258, "Material", "VerticalAlignBottom" },
    { 0xE259, "Material", "VerticalAlignCenter" },
    { 0xE25A, "Material", "VerticalAlignTop" },
    { 0xE62D, "Material", "Vibration" },
    { 0xE070, "Material", "VideoCall" },
    { 0xE071, "Material", "VideoLabel" },
    { 0xE04A, "Material", "VideoLibrary" },
    { 0xE04B, "Material", "Videocam" },
    { 0xE04C, "Material", "VideocamOff" },
    { 0xE338, "Material", "VideogameAsset" },
    { 0xE8E9, "Material", "ViewAgenda" },
    { 0xE8EA, "Material", "ViewArray" },
    { 0xE8EB, "Material", "ViewCarousel" },
    { 0xE8EC, "Material", "ViewColumn" },
    { 0xE42A, "Material", "ViewComfy" },
    { 0xE42B, "Material", "ViewCompact" },
    { 0xE8ED, "Material", "ViewDay" },
    { 0xE8EE, "Material", "ViewHeadline" },
    { 0xE8EF, "Material", "ViewList" },
    { 0xE8F0, "Material", "ViewModule" },
    { 0xE8F1, "Material", "ViewQuilt" },
    { 0xE8F2, "Material", "ViewStream" },
    { 0xE8F3, "Material", "ViewWeek" },
    { 0xE435, "Material", "Vignette" },
    { 0xE8F4, "Material", "Visibility" },
    { 0xE8F5, "Material", "VisibilityOff" },
    { 0xE62E, "Material", "VoiceChat" },
    { 0xE0D9, "Material", "Voicemail" },
    { 0xE04D, "Material", "VolumeDown" },
    { 0xE04E, "Material", "VolumeMute" },
    { 0xE04F, "Material", "VolumeOff" },
    { 0xE050, "Material", "VolumeUp" },
    { 0xE0DA, "Material", "VpnKey" },
    { 0xE62F, "Material", "VpnLock" },
    { 0xE1BC, "Material", "Wallpaper" },
    { 0xE002, "Material", "Warning" },
    { 0xE334, "Material", "Watch" },
    { 0xE924, "Material", "WatchLater" },
    { 0xE42C, "Material", "WbAuto" },
    { 0xE42D, "Material", "WbCloudy" },
    { 0xE42E, "Material", "WbIncandescent" },
    { 0xE436, "Material", "WbIridescent" },
    { 0xE430, "Material", "WbSunny" },
    { 0xE63D, "Material", "Wc" },
    { 0xE051, "Material", "Web" },
    { 0xE069, "Material", "WebAsset" },
    { 0xE16B, "Material", "Weekend" },
    { 0xE80E, "Material", "Whatshot" },
    { 0xE1BD, "Material", "Widgets" },
    { 0xE63E, "Material", "Wifi" },
    { 0xE1E1, "Material", "WifiLock" },
    { 0xE1E2, "Material", "WifiTethering" },
    { 0xE8F9, "Material", "Work" },
    { 0xE25B, "Material", "WrapText" },
    { 0xE8FA, "Material", "YoutubeSearchedFor" },
    { 0xE8FF, "Material", "ZoomIn" },
    { 0xE900, "Material", "ZoomOut" },
    { 0xE56B, "Material", "ZoomOutMap" },

    { 0xF26E, "Font Awesome Brands","_500px" },
    { 0xF368, "Font Awesome Brands","AccessibleIcon" },
    { 0xF369, "Font Awesome Brands","Accusoft" },
    { 0xF170, "Font Awesome Brands","Adn" },
    { 0xF36A, "Font Awesome Brands","Adversal" },
    { 0xF36B, "Font Awesome Brands","Affiliatetheme" },
    { 0xF36C, "Font Awesome Brands","Algolia" },
    { 0xF270, "Font Awesome Brands","Amazon" },
    { 0xF42C, "Font Awesome Brands","AmazonPay" },
    { 0xF36D, "Font Awesome Brands","Amilia" },
    { 0xF17B, "Font Awesome Brands","Android" },
    { 0xF209, "Font Awesome Brands","Angellist" },
    { 0xF36E, "Font Awesome Brands","Angrycreative" },
    { 0xF420, "Font Awesome Brands","Angular" },
    { 0xF36F, "Font Awesome Brands","AppStore" },
    { 0xF370, "Font Awesome Brands","AppStoreIos" },
    { 0xF371, "Font Awesome Brands","Apper" },
    { 0xF179, "Font Awesome Brands","Apple" },
    { 0xF415, "Font Awesome Brands","ApplePay" },
    { 0xF372, "Font Awesome Brands","Asymmetrik" },
    { 0xF373, "Font Awesome Brands","Audible" },
    { 0xF41C, "Font Awesome Brands","Autoprefixer" },
    { 0xF374, "Font Awesome Brands","Avianex" },
    { 0xF421, "Font Awesome Brands","Aviato" },
    { 0xF375, "Font Awesome Brands","Aws" },
    { 0xF2D5, "Font Awesome Brands","Bandcamp" },
    { 0xF1B4, "Font Awesome Brands","Behance" },
    { 0xF1B5, "Font Awesome Brands","BehanceSquare" },
    { 0xF378, "Font Awesome Brands","Bimobject" },
    { 0xF171, "Font Awesome Brands","Bitbucket" },
    { 0xF379, "Font Awesome Brands","Bitcoin" },
    { 0xF37A, "Font Awesome Brands","Bity" },
    { 0xF27E, "Font Awesome Brands","BlackTie" },
    { 0xF37B, "Font Awesome Brands","Blackberry" },
    { 0xF37C, "Font Awesome Brands","Blogger" },
    { 0xF37D, "Font Awesome Brands","BloggerB" },
    { 0xF293, "Font Awesome Brands","Bluetooth" },
    { 0xF294, "Font Awesome Brands","BluetoothB" },
    { 0xF15A, "Font Awesome Brands","Btc" },
    { 0xF37F, "Font Awesome Brands","Buromobelexperte" },
    { 0xF20D, "Font Awesome Brands","Buysellads" },
    { 0xF42D, "Font Awesome Brands","CcAmazonPay" },
    { 0xF1F3, "Font Awesome Brands","CcAmex" },
    { 0xF416, "Font Awesome Brands","CcApplePay" },
    { 0xF24C, "Font Awesome Brands","CcDinersClub" },
    { 0xF1F2, "Font Awesome Brands","CcDiscover" },
    { 0xF24B, "Font Awesome Brands","CcJcb" },
    { 0xF1F1, "Font Awesome Brands","CcMastercard" },
    { 0xF1F4, "Font Awesome Brands","CcPaypal" },
    { 0xF1F5, "Font Awesome Brands","CcStripe" },
    { 0xF1F0, "Font Awesome Brands","CcVisa" },
    { 0xF380, "Font Awesome Brands","Centercode" },
    { 0xF268, "Font Awesome Brands","Chrome" },
    { 0xF383, "Font Awesome Brands","Cloudscale" },
    { 0xF384, "Font Awesome Brands","Cloudsmith" },
    { 0xF385, "Font Awesome Brands","Cloudversify" },
    { 0xF1CB, "Font Awesome Brands","Codepen" },
    { 0xF284, "Font Awesome Brands","Codiepie" },
    { 0xF20E, "Font Awesome Brands","Connectdevelop" },
    { 0xF26D, "Font Awesome Brands","Contao" },
    { 0xF388, "Font Awesome Brands","Cpanel" },
    { 0xF25E, "Font Awesome Brands","CreativeCommons" },
    { 0xF4E7, "Font Awesome Brands","CreativeCommonsBy" },
    { 0xF4E8, "Font Awesome Brands","CreativeCommonsNc" },
    { 0xF4E9, "Font Awesome Brands","CreativeCommonsNcEu" },
    { 0xF4EA, "Font Awesome Brands","CreativeCommonsNcJp" },
    { 0xF4EB, "Font Awesome Brands","CreativeCommonsNd" },
    { 0xF4EC, "Font Awesome Brands","CreativeCommonsPd" },
    { 0xF4ED, "Font Awesome Brands","CreativeCommonsPdAlt" },
    { 0xF4EE, "Font Awesome Brands","CreativeCommonsRemix" },
    { 0xF4EF, "Font Awesome Brands","CreativeCommonsSa" },
    { 0xF4F0, "Font Awesome Brands","CreativeCommonsSampling" },
    { 0xF4F1, "Font Awesome Brands","CreativeCommonsSamplingPlus" },
    { 0xF4F2, "Font Awesome Brands","CreativeCommonsShare" },
    { 0xF13C, "Font Awesome Brands","Css3" },
    { 0xF38B, "Font Awesome Brands","Css3Alt" },
    { 0xF38C, "Font Awesome Brands","Cuttlefish" },
    { 0xF38D, "Font Awesome Brands","DAndD" },
    { 0xF210, "Font Awesome Brands","Dashcube" },
    { 0xF1A5, "Font Awesome Brands","Delicious" },
    { 0xF38E, "Font Awesome Brands","Deploydog" },
    { 0xF38F, "Font Awesome Brands","Deskpro" },
    { 0xF1BD, "Font Awesome Brands","Deviantart" },
    { 0xF1A6, "Font Awesome Brands","Digg" },
    { 0xF391, "Font Awesome Brands","DigitalOcean" },
    { 0xF392, "Font Awesome Brands","Discord" },
    { 0xF393, "Font Awesome Brands","Discourse" },
    { 0xF394, "Font Awesome Brands","Dochub" },
    { 0xF395, "Font Awesome Brands","Docker" },
    { 0xF396, "Font Awesome Brands","Draft2digital" },
    { 0xF17D, "Font Awesome Brands","Dribbble" },
    { 0xF397, "Font Awesome Brands","DribbbleSquare" },
    { 0xF16B, "Font Awesome Brands","Dropbox" },
    { 0xF1A9, "Font Awesome Brands","Drupal" },
    { 0xF399, "Font Awesome Brands","Dyalog" },
    { 0xF39A, "Font Awesome Brands","Earlybirds" },
    { 0xF4F4, "Font Awesome Brands","Ebay" },
    { 0xF282, "Font Awesome Brands","Edge" },
    { 0xF430, "Font Awesome Brands","Elementor" },
    { 0xF423, "Font Awesome Brands","Ember" },
    { 0xF1D1, "Font Awesome Brands","Empire" },
    { 0xF299, "Font Awesome Brands","Envira" },
    { 0xF39D, "Font Awesome Brands","Erlang" },
    { 0xF42E, "Font Awesome Brands","Ethereum" },
    { 0xF2D7, "Font Awesome Brands","Etsy" },
    { 0xF23E, "Font Awesome Brands","Expeditedssl" },
    { 0xF09A, "Font Awesome Brands","Facebook" },
    { 0xF39E, "Font Awesome Brands","FacebookF" },
    { 0xF39F, "Font Awesome Brands","FacebookMessenger" },
    { 0xF082, "Font Awesome Brands","FacebookSquare" },
    { 0xF269, "Font Awesome Brands","Firefox" },
    { 0xF2B0, "Font Awesome Brands","FirstOrder" },
    { 0xF50A, "Font Awesome Brands","FirstOrderAlt" },
    { 0xF3A1, "Font Awesome Brands","Firstdraft" },
    { 0xF16E, "Font Awesome Brands","Flickr" },
    { 0xF44D, "Font Awesome Brands","Flipboard" },
    { 0xF417, "Font Awesome Brands","Fly" },
    { 0xF2B4, "Font Awesome Brands","FontAwesome" },
    { 0xF35C, "Font Awesome Brands","FontAwesomeAlt" },
    { 0xF425, "Font Awesome Brands","FontAwesomeFlag" },
    { 0xF4E6, "Font Awesome Brands","FontAwesomeLogoFull" },
    { 0xF280, "Font Awesome Brands","Fonticons" },
    { 0xF3A2, "Font Awesome Brands","FonticonsFi" },
    { 0xF286, "Font Awesome Brands","FortAwesome" },
    { 0xF3A3, "Font Awesome Brands","FortAwesomeAlt" },
    { 0xF211, "Font Awesome Brands","Forumbee" },
    { 0xF180, "Font Awesome Brands","Foursquare" },
    { 0xF2C5, "Font Awesome Brands","FreeCodeCamp" },
    { 0xF3A4, "Font Awesome Brands","Freebsd" },
    { 0xF50B, "Font Awesome Brands","Fulcrum" },
    { 0xF50C, "Font Awesome Brands","GalacticRepublic" },
    { 0xF50D, "Font Awesome Brands","GalacticSenate" },
    { 0xF265, "Font Awesome Brands","GetPocket" },
    { 0xF260, "Font Awesome Brands","Gg" },
    { 0xF261, "Font Awesome Brands","GgCircle" },
    { 0xF1D3, "Font Awesome Brands","Git" },
    { 0xF1D2, "Font Awesome Brands","GitSquare" },
    { 0xF09B, "Font Awesome Brands","Github" },
    { 0xF113, "Font Awesome Brands","GithubAlt" },
    { 0xF092, "Font Awesome Brands","GithubSquare" },
    { 0xF3A6, "Font Awesome Brands","Gitkraken" },
    { 0xF296, "Font Awesome Brands","Gitlab" },
    { 0xF426, "Font Awesome Brands","Gitter" },
    { 0xF2A5, "Font Awesome Brands","Glide" },
    { 0xF2A6, "Font Awesome Brands","GlideG" },
    { 0xF3A7, "Font Awesome Brands","Gofore" },
    { 0xF3A8, "Font Awesome Brands","Goodreads" },
    { 0xF3A9, "Font Awesome Brands","GoodreadsG" },
    { 0xF1A0, "Font Awesome Brands","Google" },
    { 0xF3AA, "Font Awesome Brands","GoogleDrive" },
    { 0xF3AB, "Font Awesome Brands","GooglePlay" },
    { 0xF2B3, "Font Awesome Brands","GooglePlus" },
    { 0xF0D5, "Font Awesome Brands","GooglePlusG" },
    { 0xF0D4, "Font Awesome Brands","GooglePlusSquare" },
    { 0xF1EE, "Font Awesome Brands","GoogleWallet" },
    { 0xF184, "Font Awesome Brands","Gratipay" },
    { 0xF2D6, "Font Awesome Brands","Grav" },
    { 0xF3AC, "Font Awesome Brands","Gripfire" },
    { 0xF3AD, "Font Awesome Brands","Grunt" },
    { 0xF3AE, "Font Awesome Brands","Gulp" },
    { 0xF1D4, "Font Awesome Brands","HackerNews" },
    { 0xF3AF, "Font Awesome Brands","HackerNewsSquare" },
    { 0xF452, "Font Awesome Brands","Hips" },
    { 0xF3B0, "Font Awesome Brands","HireAHelper" },
    { 0xF427, "Font Awesome Brands","Hooli" },
    { 0xF592, "Font Awesome Brands","Hornbill" },
    { 0xF3B1, "Font Awesome Brands","Hotjar" },
    { 0xF27C, "Font Awesome Brands","Houzz" },
    { 0xF13B, "Font Awesome Brands","Html5" },
    { 0xF3B2, "Font Awesome Brands","Hubspot" },
    { 0xF2D8, "Font Awesome Brands","Imdb" },
    { 0xF16D, "Font Awesome Brands","Instagram" },
    { 0xF26B, "Font Awesome Brands","InternetExplorer" },
    { 0xF208, "Font Awesome Brands","Ioxhost" },
    { 0xF3B4, "Font Awesome Brands","Itunes" },
    { 0xF3B5, "Font Awesome Brands","ItunesNote" },
    { 0xF4E4, "Font Awesome Brands","Java" },
    { 0xF50E, "Font Awesome Brands","JediOrder" },
    { 0xF3B6, "Font Awesome Brands","Jenkins" },
    { 0xF3B7, "Font Awesome Brands","Joget" },
    { 0xF1AA, "Font Awesome Brands","Joomla" },
    { 0xF3B8, "Font Awesome Brands","Js" },
    { 0xF3B9, "Font Awesome Brands","JsSquare" },
    { 0xF1CC, "Font Awesome Brands","Jsfiddle" },
    { 0xF4F5, "Font Awesome Brands","Keybase" },
    { 0xF3BA, "Font Awesome Brands","Keycdn" },
    { 0xF3BB, "Font Awesome Brands","Kickstarter" },
    { 0xF3BC, "Font Awesome Brands","KickstarterK" },
    { 0xF42F, "Font Awesome Brands","Korvue" },
    { 0xF3BD, "Font Awesome Brands","Laravel" },
    { 0xF202, "Font Awesome Brands","Lastfm" },
    { 0xF203, "Font Awesome Brands","LastfmSquare" },
    { 0xF212, "Font Awesome Brands","Leanpub" },
    { 0xF41D, "Font Awesome Brands","Less" },
    { 0xF3C0, "Font Awesome Brands","Line" },
    { 0xF08C, "Font Awesome Brands","Linkedin" },
    { 0xF0E1, "Font Awesome Brands","LinkedinIn" },
    { 0xF2B8, "Font Awesome Brands","Linode" },
    { 0xF17C, "Font Awesome Brands","Linux" },
    { 0xF3C3, "Font Awesome Brands","Lyft" },
    { 0xF3C4, "Font Awesome Brands","Magento" },
    { 0xF59E, "Font Awesome Brands","Mailchimp" },
    { 0xF50F, "Font Awesome Brands","Mandalorian" },
    { 0xF4F6, "Font Awesome Brands","Mastodon" },
    { 0xF136, "Font Awesome Brands","Maxcdn" },
    { 0xF3C6, "Font Awesome Brands","Medapps" },
    { 0xF23A, "Font Awesome Brands","Medium" },
    { 0xF3C7, "Font Awesome Brands","MediumM" },
    { 0xF3C8, "Font Awesome Brands","Medrt" },
    { 0xF2E0, "Font Awesome Brands","Meetup" },
    { 0xF5A3, "Font Awesome Brands","Megaport" },
    { 0xF3CA, "Font Awesome Brands","Microsoft" },
    { 0xF3CB, "Font Awesome Brands","Mix" },
    { 0xF289, "Font Awesome Brands","Mixcloud" },
    { 0xF3CC, "Font Awesome Brands","Mizuni" },
    { 0xF285, "Font Awesome Brands","Modx" },
    { 0xF3D0, "Font Awesome Brands","Monero" },
    { 0xF3D2, "Font Awesome Brands","Napster" },
    { 0xF5A8, "Font Awesome Brands","Nimblr" },
    { 0xF418, "Font Awesome Brands","NintendoSwitch" },
    { 0xF419, "Font Awesome Brands","Node" },
    { 0xF3D3, "Font Awesome Brands","NodeJs" },
    { 0xF3D4, "Font Awesome Brands","Npm" },
    { 0xF3D5, "Font Awesome Brands","Ns8" },
    { 0xF3D6, "Font Awesome Brands","Nutritionix" },
    { 0xF263, "Font Awesome Brands","Odnoklassniki" },
    { 0xF264, "Font Awesome Brands","OdnoklassnikiSquare" },
    { 0xF510, "Font Awesome Brands","OldRepublic" },
    { 0xF23D, "Font Awesome Brands","Opencart" },
    { 0xF19B, "Font Awesome Brands","Openid" },
    { 0xF26A, "Font Awesome Brands","Opera" },
    { 0xF23C, "Font Awesome Brands","OptinMonster" },
    { 0xF41A, "Font Awesome Brands","Osi" },
    { 0xF3D7, "Font Awesome Brands","Page4" },
    { 0xF18C, "Font Awesome Brands","Pagelines" },
    { 0xF3D8, "Font Awesome Brands","Palfed" },
    { 0xF3D9, "Font Awesome Brands","Patreon" },
    { 0xF1ED, "Font Awesome Brands","Paypal" },
    { 0xF3DA, "Font Awesome Brands","Periscope" },
    { 0xF3DB, "Font Awesome Brands","Phabricator" },
    { 0xF3DC, "Font Awesome Brands","PhoenixFramework" },
    { 0xF511, "Font Awesome Brands","PhoenixSquadron" },
    { 0xF457, "Font Awesome Brands","Php" },
    { 0xF2AE, "Font Awesome Brands","PiedPiper" },
    { 0xF1A8, "Font Awesome Brands","PiedPiperAlt" },
    { 0xF4E5, "Font Awesome Brands","PiedPiperHat" },
    { 0xF1A7, "Font Awesome Brands","PiedPiperPp" },
    { 0xF0D2, "Font Awesome Brands","Pinterest" },
    { 0xF231, "Font Awesome Brands","PinterestP" },
    { 0xF0D3, "Font Awesome Brands","PinterestSquare" },
    { 0xF3DF, "Font Awesome Brands","Playstation" },
    { 0xF288, "Font Awesome Brands","ProductHunt" },
    { 0xF3E1, "Font Awesome Brands","Pushed" },
    { 0xF3E2, "Font Awesome Brands","Python" },
    { 0xF1D6, "Font Awesome Brands","Qq" },
    { 0xF459, "Font Awesome Brands","Quinscape" },
    { 0xF2C4, "Font Awesome Brands","Quora" },
    { 0xF4F7, "Font Awesome Brands","RProject" },
    { 0xF2D9, "Font Awesome Brands","Ravelry" },
    { 0xF41B, "Font Awesome Brands","React" },
    { 0xF4D5, "Font Awesome Brands","Readme" },
    { 0xF1D0, "Font Awesome Brands","Rebel" },
    { 0xF3E3, "Font Awesome Brands","RedRiver" },
    { 0xF1A1, "Font Awesome Brands","Reddit" },
    { 0xF281, "Font Awesome Brands","RedditAlien" },
    { 0xF1A2, "Font Awesome Brands","RedditSquare" },
    { 0xF3E4, "Font Awesome Brands","Rendact" },
    { 0xF18B, "Font Awesome Brands","Renren" },
    { 0xF3E6, "Font Awesome Brands","Replyd" },
    { 0xF4F8, "Font Awesome Brands","Researchgate" },
    { 0xF3E7, "Font Awesome Brands","Resolving" },
    { 0xF3E8, "Font Awesome Brands","Rocketchat" },
    { 0xF3E9, "Font Awesome Brands","Rockrms" },
    { 0xF267, "Font Awesome Brands","Safari" },
    { 0xF41E, "Font Awesome Brands","Sass" },
    { 0xF3EA, "Font Awesome Brands","Schlix" },
    { 0xF28A, "Font Awesome Brands","Scribd" },
    { 0xF3EB, "Font Awesome Brands","Searchengin" },
    { 0xF2DA, "Font Awesome Brands","Sellcast" },
    { 0xF213, "Font Awesome Brands","Sellsy" },
    { 0xF3EC, "Font Awesome Brands","Servicestack" },
    { 0xF214, "Font Awesome Brands","Shirtsinbulk" },
    { 0xF5B5, "Font Awesome Brands","Shopware" },
    { 0xF215, "Font Awesome Brands","Simplybuilt" },
    { 0xF3EE, "Font Awesome Brands","Sistrix" },
    { 0xF512, "Font Awesome Brands","Sith" },
    { 0xF216, "Font Awesome Brands","Skyatlas" },
    { 0xF17E, "Font Awesome Brands","Skype" },
    { 0xF198, "Font Awesome Brands","Slack" },
    { 0xF3EF, "Font Awesome Brands","SlackHash" },
    { 0xF1E7, "Font Awesome Brands","Slideshare" },
    { 0xF2AB, "Font Awesome Brands","Snapchat" },
    { 0xF2AC, "Font Awesome Brands","SnapchatGhost" },
    { 0xF2AD, "Font Awesome Brands","SnapchatSquare" },
    { 0xF1BE, "Font Awesome Brands","Soundcloud" },
    { 0xF3F3, "Font Awesome Brands","Speakap" },
    { 0xF1BC, "Font Awesome Brands","Spotify" },
    { 0xF5BE, "Font Awesome Brands","Squarespace" },
    { 0xF18D, "Font Awesome Brands","StackExchange" },
    { 0xF16C, "Font Awesome Brands","StackOverflow" },
    { 0xF3F5, "Font Awesome Brands","Staylinked" },
    { 0xF1B6, "Font Awesome Brands","Steam" },
    { 0xF1B7, "Font Awesome Brands","SteamSquare" },
    { 0xF3F6, "Font Awesome Brands","SteamSymbol" },
    { 0xF3F7, "Font Awesome Brands","StickerMule" },
    { 0xF428, "Font Awesome Brands","Strava" },
    { 0xF429, "Font Awesome Brands","Stripe" },
    { 0xF42A, "Font Awesome Brands","StripeS" },
    { 0xF3F8, "Font Awesome Brands","Studiovinari" },
    { 0xF1A4, "Font Awesome Brands","Stumbleupon" },
    { 0xF1A3, "Font Awesome Brands","StumbleuponCircle" },
    { 0xF2DD, "Font Awesome Brands","Superpowers" },
    { 0xF3F9, "Font Awesome Brands","Supple" },
    { 0xF4F9, "Font Awesome Brands","Teamspeak" },
    { 0xF2C6, "Font Awesome Brands","Telegram" },
    { 0xF3FE, "Font Awesome Brands","TelegramPlane" },
    { 0xF1D5, "Font Awesome Brands","TencentWeibo" },
    { 0xF5C6, "Font Awesome Brands","Themeco" },
    { 0xF2B2, "Font Awesome Brands","Themeisle" },
    { 0xF513, "Font Awesome Brands","TradeFederation" },
    { 0xF181, "Font Awesome Brands","Trello" },
    { 0xF262, "Font Awesome Brands","Tripadvisor" },
    { 0xF173, "Font Awesome Brands","Tumblr" },
    { 0xF174, "Font Awesome Brands","TumblrSquare" },
    { 0xF1E8, "Font Awesome Brands","Twitch" },
    { 0xF099, "Font Awesome Brands","Twitter" },
    { 0xF081, "Font Awesome Brands","TwitterSquare" },
    { 0xF42B, "Font Awesome Brands","Typo3" },
    { 0xF402, "Font Awesome Brands","Uber" },
    { 0xF403, "Font Awesome Brands","Uikit" },
    { 0xF404, "Font Awesome Brands","Uniregistry" },
    { 0xF405, "Font Awesome Brands","Untappd" },
    { 0xF287, "Font Awesome Brands","Usb" },
    { 0xF407, "Font Awesome Brands","Ussunnah" },
    { 0xF408, "Font Awesome Brands","Vaadin" },
    { 0xF237, "Font Awesome Brands","Viacoin" },
    { 0xF2A9, "Font Awesome Brands","Viadeo" },
    { 0xF2AA, "Font Awesome Brands","ViadeoSquare" },
    { 0xF409, "Font Awesome Brands","Viber" },
    { 0xF40A, "Font Awesome Brands","Vimeo" },
    { 0xF194, "Font Awesome Brands","VimeoSquare" },
    { 0xF27D, "Font Awesome Brands","VimeoV" },
    { 0xF1CA, "Font Awesome Brands","Vine" },
    { 0xF189, "Font Awesome Brands","Vk" },
    { 0xF40B, "Font Awesome Brands","Vnv" },
    { 0xF41F, "Font Awesome Brands","Vuejs" },
    { 0xF5CC, "Font Awesome Brands","Weebly" },
    { 0xF18A, "Font Awesome Brands","Weibo" },
    { 0xF1D7, "Font Awesome Brands","Weixin" },
    { 0xF232, "Font Awesome Brands","Whatsapp" },
    { 0xF40C, "Font Awesome Brands","WhatsappSquare" },
    { 0xF40D, "Font Awesome Brands","Whmcs" },
    { 0xF266, "Font Awesome Brands","WikipediaW" },
    { 0xF17A, "Font Awesome Brands","Windows" },
    { 0xF5CF, "Font Awesome Brands","Wix" },
    { 0xF514, "Font Awesome Brands","WolfPackBattalion" },
    { 0xF19A, "Font Awesome Brands","Wordpress" },
    { 0xF411, "Font Awesome Brands","WordpressSimple" },
    { 0xF297, "Font Awesome Brands","Wpbeginner" },
    { 0xF2DE, "Font Awesome Brands","Wpexplorer" },
    { 0xF298, "Font Awesome Brands","Wpforms" },
    { 0xF412, "Font Awesome Brands","Xbox" },
    { 0xF168, "Font Awesome Brands","Xing" },
    { 0xF169, "Font Awesome Brands","XingSquare" },
    { 0xF23B, "Font Awesome Brands","YCombinator" },
    { 0xF19E, "Font Awesome Brands","Yahoo" },
    { 0xF413, "Font Awesome Brands","Yandex" },
    { 0xF414, "Font Awesome Brands","YandexInternational" },
    { 0xF1E9, "Font Awesome Brands","Yelp" },
    { 0xF2B1, "Font Awesome Brands","Yoast" },
    { 0xF167, "Font Awesome Brands","Youtube" },
    { 0xF431, "Font Awesome Brands","YoutubeSquare" },

    { 0xF2B9, "Font Awesome", "AddressBook" },
    { 0xF2BB, "Font Awesome", "AddressCard" },
    { 0xF042, "Font Awesome", "Adjust" },
    { 0xF037, "Font Awesome", "AlignCenter" },
    { 0xF039, "Font Awesome", "AlignJustify" },
    { 0xF036, "Font Awesome", "AlignLeft" },
    { 0xF038, "Font Awesome", "AlignRight" },
    { 0xF461, "Font Awesome", "Allergies" },
    { 0xF0F9, "Font Awesome", "Ambulance" },
    { 0xF2A3, "Font Awesome", "AmericanSignLanguageInterpreting" },
    { 0xF13D, "Font Awesome", "Anchor" },
    { 0xF103, "Font Awesome", "AngleDoubleDown" },
    { 0xF100, "Font Awesome", "AngleDoubleLeft" },
    { 0xF101, "Font Awesome", "AngleDoubleRight" },
    { 0xF102, "Font Awesome", "AngleDoubleUp" },
    { 0xF107, "Font Awesome", "AngleDown" },
    { 0xF104, "Font Awesome", "AngleLeft" },
    { 0xF105, "Font Awesome", "AngleRight" },
    { 0xF106, "Font Awesome", "AngleUp" },
    { 0xF556, "Font Awesome", "Angry" },
    { 0xF187, "Font Awesome", "Archive" },
    { 0xF557, "Font Awesome", "Archway" },
    { 0xF358, "Font Awesome", "ArrowAltCircleDown" },
    { 0xF359, "Font Awesome", "ArrowAltCircleLeft" },
    { 0xF35A, "Font Awesome", "ArrowAltCircleRight" },
    { 0xF35B, "Font Awesome", "ArrowAltCircleUp" },
    { 0xF0AB, "Font Awesome", "ArrowCircleDown" },
    { 0xF0A8, "Font Awesome", "ArrowCircleLeft" },
    { 0xF0A9, "Font Awesome", "ArrowCircleRight" },
    { 0xF0AA, "Font Awesome", "ArrowCircleUp" },
    { 0xF063, "Font Awesome", "ArrowDown" },
    { 0xF060, "Font Awesome", "ArrowLeft" },
    { 0xF061, "Font Awesome", "ArrowRight" },
    { 0xF062, "Font Awesome", "ArrowUp" },
    { 0xF0B2, "Font Awesome", "ArrowsAlt" },
    { 0xF337, "Font Awesome", "ArrowsAltH" },
    { 0xF338, "Font Awesome", "ArrowsAltV" },
    { 0xF2A2, "Font Awesome", "AssistiveListeningSystems" },
    { 0xF069, "Font Awesome", "Asterisk" },
    { 0xF1FA, "Font Awesome", "At" },
    { 0xF558, "Font Awesome", "Atlas" },
    { 0xF29E, "Font Awesome", "AudioDescription" },
    { 0xF559, "Font Awesome", "Award" },
    { 0xF55A, "Font Awesome", "Backspace" },
    { 0xF04A, "Font Awesome", "Backward" },
    { 0xF24E, "Font Awesome", "BalanceScale" },
    { 0xF05E, "Font Awesome", "Ban" },
    { 0xF462, "Font Awesome", "BandAid" },
    { 0xF02A, "Font Awesome", "Barcode" },
    { 0xF0C9, "Font Awesome", "Bars" },
    { 0xF433, "Font Awesome", "BaseballBall" },
    { 0xF434, "Font Awesome", "BasketballBall" },
    { 0xF2CD, "Font Awesome", "Bath" },
    { 0xF244, "Font Awesome", "BatteryEmpty" },
    { 0xF240, "Font Awesome", "BatteryFull" },
    { 0xF242, "Font Awesome", "BatteryHalf" },
    { 0xF243, "Font Awesome", "BatteryQuarter" },
    { 0xF241, "Font Awesome", "BatteryThreeQuarters" },
    { 0xF236, "Font Awesome", "Bed" },
    { 0xF0FC, "Font Awesome", "Beer" },
    { 0xF0F3, "Font Awesome", "Bell" },
    { 0xF1F6, "Font Awesome", "BellSlash" },
    { 0xF55B, "Font Awesome", "BezierCurve" },
    { 0xF206, "Font Awesome", "Bicycle" },
    { 0xF1E5, "Font Awesome", "Binoculars" },
    { 0xF1FD, "Font Awesome", "BirthdayCake" },
    { 0xF517, "Font Awesome", "Blender" },
    { 0xF29D, "Font Awesome", "Blind" },
    { 0xF032, "Font Awesome", "Bold" },
    { 0xF0E7, "Font Awesome", "Bolt" },
    { 0xF1E2, "Font Awesome", "Bomb" },
    { 0xF55C, "Font Awesome", "Bong" },
    { 0xF02D, "Font Awesome", "Book" },
    { 0xF518, "Font Awesome", "BookOpen" },
    { 0xF02E, "Font Awesome", "Bookmark" },
    { 0xF436, "Font Awesome", "BowlingBall" },
    { 0xF466, "Font Awesome", "Box" },
    { 0xF49E, "Font Awesome", "BoxOpen" },
    { 0xF468, "Font Awesome", "Boxes" },
    { 0xF2A1, "Font Awesome", "Braille" },
    { 0xF0B1, "Font Awesome", "Briefcase" },
    { 0xF469, "Font Awesome", "BriefcaseMedical" },
    { 0xF519, "Font Awesome", "BroadcastTower" },
    { 0xF51A, "Font Awesome", "Broom" },
    { 0xF55D, "Font Awesome", "Brush" },
    { 0xF188, "Font Awesome", "Bug" },
    { 0xF1AD, "Font Awesome", "Building" },
    { 0xF0A1, "Font Awesome", "Bullhorn" },
    { 0xF140, "Font Awesome", "Bullseye" },
    { 0xF46A, "Font Awesome", "Burn" },
    { 0xF207, "Font Awesome", "Bus" },
    { 0xF55E, "Font Awesome", "BusAlt" },
    { 0xF1EC, "Font Awesome", "Calculator" },
    { 0xF133, "Font Awesome", "Calendar" },
    { 0xF073, "Font Awesome", "CalendarAlt" },
    { 0xF274, "Font Awesome", "CalendarCheck" },
    { 0xF272, "Font Awesome", "CalendarMinus" },
    { 0xF271, "Font Awesome", "CalendarPlus" },
    { 0xF273, "Font Awesome", "CalendarTimes" },
    { 0xF030, "Font Awesome", "Camera" },
    { 0xF083, "Font Awesome", "CameraRetro" },
    { 0xF55F, "Font Awesome", "Cannabis" },
    { 0xF46B, "Font Awesome", "Capsules" },
    { 0xF1B9, "Font Awesome", "Car" },
    { 0xF0D7, "Font Awesome", "CaretDown" },
    { 0xF0D9, "Font Awesome", "CaretLeft" },
    { 0xF0DA, "Font Awesome", "CaretRight" },
    { 0xF150, "Font Awesome", "CaretSquareDown" },
    { 0xF191, "Font Awesome", "CaretSquareLeft" },
    { 0xF152, "Font Awesome", "CaretSquareRight" },
    { 0xF151, "Font Awesome", "CaretSquareUp" },
    { 0xF0D8, "Font Awesome", "CaretUp" },
    { 0xF218, "Font Awesome", "CartArrowDown" },
    { 0xF217, "Font Awesome", "CartPlus" },
    { 0xF0A3, "Font Awesome", "Certificate" },
    { 0xF51B, "Font Awesome", "Chalkboard" },
    { 0xF51C, "Font Awesome", "ChalkboardTeacher" },
    { 0xF1FE, "Font Awesome", "ChartArea" },
    { 0xF080, "Font Awesome", "ChartBar" },
    { 0xF201, "Font Awesome", "ChartLine" },
    { 0xF200, "Font Awesome", "ChartPie" },
    { 0xF00C, "Font Awesome", "Check" },
    { 0xF058, "Font Awesome", "CheckCircle" },
    { 0xF560, "Font Awesome", "CheckDouble" },
    { 0xF14A, "Font Awesome", "CheckSquare" },
    { 0xF439, "Font Awesome", "Chess" },
    { 0xF43A, "Font Awesome", "ChessBishop" },
    { 0xF43C, "Font Awesome", "ChessBoard" },
    { 0xF43F, "Font Awesome", "ChessKing" },
    { 0xF441, "Font Awesome", "ChessKnight" },
    { 0xF443, "Font Awesome", "ChessPawn" },
    { 0xF445, "Font Awesome", "ChessQueen" },
    { 0xF447, "Font Awesome", "ChessRook" },
    { 0xF13A, "Font Awesome", "ChevronCircleDown" },
    { 0xF137, "Font Awesome", "ChevronCircleLeft" },
    { 0xF138, "Font Awesome", "ChevronCircleRight" },
    { 0xF139, "Font Awesome", "ChevronCircleUp" },
    { 0xF078, "Font Awesome", "ChevronDown" },
    { 0xF053, "Font Awesome", "ChevronLeft" },
    { 0xF054, "Font Awesome", "ChevronRight" },
    { 0xF077, "Font Awesome", "ChevronUp" },
    { 0xF1AE, "Font Awesome", "Child" },
    { 0xF51D, "Font Awesome", "Church" },
    { 0xF111, "Font Awesome", "Circle" },
    { 0xF1CE, "Font Awesome", "CircleNotch" },
    { 0xF328, "Font Awesome", "Clipboard" },
    { 0xF46C, "Font Awesome", "ClipboardCheck" },
    { 0xF46D, "Font Awesome", "ClipboardList" },
    { 0xF017, "Font Awesome", "Clock" },
    { 0xF24D, "Font Awesome", "Clone" },
    { 0xF20A, "Font Awesome", "ClosedCaptioning" },
    { 0xF0C2, "Font Awesome", "Cloud" },
    { 0xF381, "Font Awesome", "CloudDownloadAlt" },
    { 0xF382, "Font Awesome", "CloudUploadAlt" },
    { 0xF561, "Font Awesome", "Cocktail" },
    { 0xF121, "Font Awesome", "Code" },
    { 0xF126, "Font Awesome", "CodeBranch" },
    { 0xF0F4, "Font Awesome", "Coffee" },
    { 0xF013, "Font Awesome", "Cog" },
    { 0xF085, "Font Awesome", "Cogs" },
    { 0xF51E, "Font Awesome", "Coins" },
    { 0xF0DB, "Font Awesome", "Columns" },
    { 0xF075, "Font Awesome", "Comment" },
    { 0xF27A, "Font Awesome", "CommentAlt" },
    { 0xF4AD, "Font Awesome", "CommentDots" },
    { 0xF4B3, "Font Awesome", "CommentSlash" },
    { 0xF086, "Font Awesome", "Comments" },
    { 0xF51F, "Font Awesome", "CompactDisc" },
    { 0xF14E, "Font Awesome", "Compass" },
    { 0xF066, "Font Awesome", "Compress" },
    { 0xF562, "Font Awesome", "ConciergeBell" },
    { 0xF563, "Font Awesome", "Cookie" },
    { 0xF564, "Font Awesome", "CookieBite" },
    { 0xF0C5, "Font Awesome", "Copy" },
    { 0xF1F9, "Font Awesome", "Copyright" },
    { 0xF4B8, "Font Awesome", "Couch" },
    { 0xF09D, "Font Awesome", "CreditCard" },
    { 0xF125, "Font Awesome", "Crop" },
    { 0xF565, "Font Awesome", "CropAlt" },
    { 0xF05B, "Font Awesome", "Crosshairs" },
    { 0xF520, "Font Awesome", "Crow" },
    { 0xF521, "Font Awesome", "Crown" },
    { 0xF1B2, "Font Awesome", "Cube" },
    { 0xF1B3, "Font Awesome", "Cubes" },
    { 0xF0C4, "Font Awesome", "Cut" },
    { 0xF1C0, "Font Awesome", "Database" },
    { 0xF2A4, "Font Awesome", "Deaf" },
    { 0xF108, "Font Awesome", "Desktop" },
    { 0xF470, "Font Awesome", "Diagnoses" },
    { 0xF522, "Font Awesome", "Dice" },
    { 0xF523, "Font Awesome", "DiceFive" },
    { 0xF524, "Font Awesome", "DiceFour" },
    { 0xF525, "Font Awesome", "DiceOne" },
    { 0xF526, "Font Awesome", "DiceSix" },
    { 0xF527, "Font Awesome", "DiceThree" },
    { 0xF528, "Font Awesome", "DiceTwo" },
    { 0xF566, "Font Awesome", "DigitalTachograph" },
    { 0xF529, "Font Awesome", "Divide" },
    { 0xF567, "Font Awesome", "Dizzy" },
    { 0xF471, "Font Awesome", "Dna" },
    { 0xF155, "Font Awesome", "DollarSign" },
    { 0xF472, "Font Awesome", "Dolly" },
    { 0xF474, "Font Awesome", "DollyFlatbed" },
    { 0xF4B9, "Font Awesome", "Donate" },
    { 0xF52A, "Font Awesome", "DoorClosed" },
    { 0xF52B, "Font Awesome", "DoorOpen" },
    { 0xF192, "Font Awesome", "DotCircle" },
    { 0xF4BA, "Font Awesome", "Dove" },
    { 0xF019, "Font Awesome", "Download" },
    { 0xF568, "Font Awesome", "DraftingCompass" },
    { 0xF569, "Font Awesome", "Drum" },
    { 0xF56A, "Font Awesome", "DrumSteelpan" },
    { 0xF44B, "Font Awesome", "Dumbbell" },
    { 0xF044, "Font Awesome", "Edit" },
    { 0xF052, "Font Awesome", "Eject" },
    { 0xF141, "Font Awesome", "EllipsisH" },
    { 0xF142, "Font Awesome", "EllipsisV" },
    { 0xF0E0, "Font Awesome", "Envelope" },
    { 0xF2B6, "Font Awesome", "EnvelopeOpen" },
    { 0xF199, "Font Awesome", "EnvelopeSquare" },
    { 0xF52C, "Font Awesome", "Equals" },
    { 0xF12D, "Font Awesome", "Eraser" },
    { 0xF153, "Font Awesome", "EuroSign" },
    { 0xF362, "Font Awesome", "ExchangeAlt" },
    { 0xF12A, "Font Awesome", "Exclamation" },
    { 0xF06A, "Font Awesome", "ExclamationCircle" },
    { 0xF071, "Font Awesome", "ExclamationTriangle" },
    { 0xF065, "Font Awesome", "Expand" },
    { 0xF31E, "Font Awesome", "ExpandArrowsAlt" },
    { 0xF35D, "Font Awesome", "ExternalLinkAlt" },
    { 0xF360, "Font Awesome", "ExternalLinkSquareAlt" },
    { 0xF06E, "Font Awesome", "Eye" },
    { 0xF1FB, "Font Awesome", "EyeDropper" },
    { 0xF070, "Font Awesome", "EyeSlash" },
    { 0xF049, "Font Awesome", "FastBackward" },
    { 0xF050, "Font Awesome", "FastForward" },
    { 0xF1AC, "Font Awesome", "Fax" },
    { 0xF52D, "Font Awesome", "Feather" },
    { 0xF56B, "Font Awesome", "FeatherAlt" },
    { 0xF182, "Font Awesome", "Female" },
    { 0xF0FB, "Font Awesome", "FighterJet" },
    { 0xF15B, "Font Awesome", "File" },
    { 0xF15C, "Font Awesome", "FileAlt" },
    { 0xF1C6, "Font Awesome", "FileArchive" },
    { 0xF1C7, "Font Awesome", "FileAudio" },
    { 0xF1C9, "Font Awesome", "FileCode" },
    { 0xF56C, "Font Awesome", "FileContract" },
    { 0xF56D, "Font Awesome", "FileDownload" },
    { 0xF1C3, "Font Awesome", "FileExcel" },
    { 0xF56E, "Font Awesome", "FileExport" },
    { 0xF1C5, "Font Awesome", "FileImage" },
    { 0xF56F, "Font Awesome", "FileImport" },
    { 0xF570, "Font Awesome", "FileInvoice" },
    { 0xF571, "Font Awesome", "FileInvoiceDollar" },
    { 0xF477, "Font Awesome", "FileMedical" },
    { 0xF478, "Font Awesome", "FileMedicalAlt" },
    { 0xF1C1, "Font Awesome", "FilePdf" },
    { 0xF1C4, "Font Awesome", "FilePowerpoint" },
    { 0xF572, "Font Awesome", "FilePrescription" },
    { 0xF573, "Font Awesome", "FileSignature" },
    { 0xF574, "Font Awesome", "FileUpload" },
    { 0xF1C8, "Font Awesome", "FileVideo" },
    { 0xF1C2, "Font Awesome", "FileWord" },
    { 0xF575, "Font Awesome", "Fill" },
    { 0xF576, "Font Awesome", "FillDrip" },
    { 0xF008, "Font Awesome", "Film" },
    { 0xF0B0, "Font Awesome", "Filter" },
    { 0xF577, "Font Awesome", "Fingerprint" },
    { 0xF06D, "Font Awesome", "Fire" },
    { 0xF134, "Font Awesome", "FireExtinguisher" },
    { 0xF479, "Font Awesome", "FirstAid" },
    { 0xF578, "Font Awesome", "Fish" },
    { 0xF024, "Font Awesome", "Flag" },
    { 0xF11E, "Font Awesome", "FlagCheckered" },
    { 0xF0C3, "Font Awesome", "Flask" },
    { 0xF579, "Font Awesome", "Flushed" },
    { 0xF07B, "Font Awesome", "Folder" },
    { 0xF07C, "Font Awesome", "FolderOpen" },
    { 0xF031, "Font Awesome", "Font" },
    { 0xF4E6, "Font Awesome", "FontAwesomeLogoFull" },
    { 0xF44E, "Font Awesome", "FootballBall" },
    { 0xF04E, "Font Awesome", "Forward" },
    { 0xF52E, "Font Awesome", "Frog" },
    { 0xF119, "Font Awesome", "Frown" },
    { 0xF57A, "Font Awesome", "FrownOpen" },
    { 0xF1E3, "Font Awesome", "Futbol" },
    { 0xF11B, "Font Awesome", "Gamepad" },
    { 0xF52F, "Font Awesome", "GasPump" },
    { 0xF0E3, "Font Awesome", "Gavel" },
    { 0xF3A5, "Font Awesome", "Gem" },
    { 0xF22D, "Font Awesome", "Genderless" },
    { 0xF06B, "Font Awesome", "Gift" },
    { 0xF000, "Font Awesome", "GlassMartini" },
    { 0xF57B, "Font Awesome", "GlassMartiniAlt" },
    { 0xF530, "Font Awesome", "Glasses" },
    { 0xF0AC, "Font Awesome", "Globe" },
    { 0xF57C, "Font Awesome", "GlobeAfrica" },
    { 0xF57D, "Font Awesome", "GlobeAmericas" },
    { 0xF57E, "Font Awesome", "GlobeAsia" },
    { 0xF450, "Font Awesome", "GolfBall" },
    { 0xF19D, "Font Awesome", "GraduationCap" },
    { 0xF531, "Font Awesome", "GreaterThan" },
    { 0xF532, "Font Awesome", "GreaterThanEqual" },
    { 0xF57F, "Font Awesome", "Grimace" },
    { 0xF580, "Font Awesome", "Grin" },
    { 0xF581, "Font Awesome", "GrinAlt" },
    { 0xF582, "Font Awesome", "GrinBeam" },
    { 0xF583, "Font Awesome", "GrinBeamSweat" },
    { 0xF584, "Font Awesome", "GrinHearts" },
    { 0xF585, "Font Awesome", "GrinSquint" },
    { 0xF586, "Font Awesome", "GrinSquintTears" },
    { 0xF587, "Font Awesome", "GrinStars" },
    { 0xF588, "Font Awesome", "GrinTears" },
    { 0xF589, "Font Awesome", "GrinTongue" },
    { 0xF58A, "Font Awesome", "GrinTongueSquint" },
    { 0xF58B, "Font Awesome", "GrinTongueWink" },
    { 0xF58C, "Font Awesome", "GrinWink" },
    { 0xF58D, "Font Awesome", "GripHorizontal" },
    { 0xF58E, "Font Awesome", "GripVertical" },
    { 0xF0FD, "Font Awesome", "HSquare" },
    { 0xF4BD, "Font Awesome", "HandHolding" },
    { 0xF4BE, "Font Awesome", "HandHoldingHeart" },
    { 0xF4C0, "Font Awesome", "HandHoldingUsd" },
    { 0xF258, "Font Awesome", "HandLizard" },
    { 0xF256, "Font Awesome", "HandPaper" },
    { 0xF25B, "Font Awesome", "HandPeace" },
    { 0xF0A7, "Font Awesome", "HandPointDown" },
    { 0xF0A5, "Font Awesome", "HandPointLeft" },
    { 0xF0A4, "Font Awesome", "HandPointRight" },
    { 0xF0A6, "Font Awesome", "HandPointUp" },
    { 0xF25A, "Font Awesome", "HandPointer" },
    { 0xF255, "Font Awesome", "HandRock" },
    { 0xF257, "Font Awesome", "HandScissors" },
    { 0xF259, "Font Awesome", "HandSpock" },
    { 0xF4C2, "Font Awesome", "Hands" },
    { 0xF4C4, "Font Awesome", "HandsHelping" },
    { 0xF2B5, "Font Awesome", "Handshake" },
    { 0xF292, "Font Awesome", "Hashtag" },
    { 0xF0A0, "Font Awesome", "Hdd" },
    { 0xF1DC, "Font Awesome", "Heading" },
    { 0xF025, "Font Awesome", "Headphones" },
    { 0xF58F, "Font Awesome", "HeadphonesAlt" },
    { 0xF590, "Font Awesome", "Headset" },
    { 0xF004, "Font Awesome", "Heart" },
    { 0xF21E, "Font Awesome", "Heartbeat" },
    { 0xF533, "Font Awesome", "Helicopter" },
    { 0xF591, "Font Awesome", "Highlighter" },
    { 0xF1DA, "Font Awesome", "History" },
    { 0xF453, "Font Awesome", "HockeyPuck" },
    { 0xF015, "Font Awesome", "Home" },
    { 0xF0F8, "Font Awesome", "Hospital" },
    { 0xF47D, "Font Awesome", "HospitalAlt" },
    { 0xF47E, "Font Awesome", "HospitalSymbol" },
    { 0xF593, "Font Awesome", "HotTub" },
    { 0xF594, "Font Awesome", "Hotel" },
    { 0xF254, "Font Awesome", "Hourglass" },
    { 0xF253, "Font Awesome", "HourglassEnd" },
    { 0xF252, "Font Awesome", "HourglassHalf" },
    { 0xF251, "Font Awesome", "HourglassStart" },
    { 0xF246, "Font Awesome", "ICursor" },
    { 0xF2C1, "Font Awesome", "IdBadge" },
    { 0xF2C2, "Font Awesome", "IdCard" },
    { 0xF47F, "Font Awesome", "IdCardAlt" },
    { 0xF03E, "Font Awesome", "Image" },
    { 0xF302, "Font Awesome", "Images" },
    { 0xF01C, "Font Awesome", "Inbox" },
    { 0xF03C, "Font Awesome", "Indent" },
    { 0xF275, "Font Awesome", "Industry" },
    { 0xF534, "Font Awesome", "Infinity" },
    { 0xF129, "Font Awesome", "Info" },
    { 0xF05A, "Font Awesome", "InfoCircle" },
    { 0xF033, "Font Awesome", "Italic" },
    { 0xF595, "Font Awesome", "Joint" },
    { 0xF084, "Font Awesome", "Key" },
    { 0xF11C, "Font Awesome", "Keyboard" },
    { 0xF596, "Font Awesome", "Kiss" },
    { 0xF597, "Font Awesome", "KissBeam" },
    { 0xF598, "Font Awesome", "KissWinkHeart" },
    { 0xF535, "Font Awesome", "KiwiBird" },
    { 0xF1AB, "Font Awesome", "Language" },
    { 0xF109, "Font Awesome", "Laptop" },
    { 0xF599, "Font Awesome", "Laugh" },
    { 0xF59A, "Font Awesome", "LaughBeam" },
    { 0xF59B, "Font Awesome", "LaughSquint" },
    { 0xF59C, "Font Awesome", "LaughWink" },
    { 0xF06C, "Font Awesome", "Leaf" },
    { 0xF094, "Font Awesome", "Lemon" },
    { 0xF536, "Font Awesome", "LessThan" },
    { 0xF537, "Font Awesome", "LessThanEqual" },
    { 0xF3BE, "Font Awesome", "LevelDownAlt" },
    { 0xF3BF, "Font Awesome", "LevelUpAlt" },
    { 0xF1CD, "Font Awesome", "LifeRing" },
    { 0xF0EB, "Font Awesome", "Lightbulb" },
    { 0xF0C1, "Font Awesome", "Link" },
    { 0xF195, "Font Awesome", "LiraSign" },
    { 0xF03A, "Font Awesome", "List" },
    { 0xF022, "Font Awesome", "ListAlt" },
    { 0xF0CB, "Font Awesome", "ListOl" },
    { 0xF0CA, "Font Awesome", "ListUl" },
    { 0xF124, "Font Awesome", "LocationArrow" },
    { 0xF023, "Font Awesome", "Lock" },
    { 0xF3C1, "Font Awesome", "LockOpen" },
    { 0xF309, "Font Awesome", "LongArrowAltDown" },
    { 0xF30A, "Font Awesome", "LongArrowAltLeft" },
    { 0xF30B, "Font Awesome", "LongArrowAltRight" },
    { 0xF30C, "Font Awesome", "LongArrowAltUp" },
    { 0xF2A8, "Font Awesome", "LowVision" },
    { 0xF59D, "Font Awesome", "LuggageCart" },
    { 0xF0D0, "Font Awesome", "Magic" },
    { 0xF076, "Font Awesome", "Magnet" },
    { 0xF183, "Font Awesome", "Male" },
    { 0xF279, "Font Awesome", "Map" },
    { 0xF59F, "Font Awesome", "MapMarked" },
    { 0xF5A0, "Font Awesome", "MapMarkedAlt" },
    { 0xF041, "Font Awesome", "MapMarker" },
    { 0xF3C5, "Font Awesome", "MapMarkerAlt" },
    { 0xF276, "Font Awesome", "MapPin" },
    { 0xF277, "Font Awesome", "MapSigns" },
    { 0xF5A1, "Font Awesome", "Marker" },
    { 0xF222, "Font Awesome", "Mars" },
    { 0xF227, "Font Awesome", "MarsDouble" },
    { 0xF229, "Font Awesome", "MarsStroke" },
    { 0xF22B, "Font Awesome", "MarsStrokeH" },
    { 0xF22A, "Font Awesome", "MarsStrokeV" },
    { 0xF5A2, "Font Awesome", "Medal" },
    { 0xF0FA, "Font Awesome", "Medkit" },
    { 0xF11A, "Font Awesome", "Meh" },
    { 0xF5A4, "Font Awesome", "MehBlank" },
    { 0xF5A5, "Font Awesome", "MehRollingEyes" },
    { 0xF538, "Font Awesome", "Memory" },
    { 0xF223, "Font Awesome", "Mercury" },
    { 0xF2DB, "Font Awesome", "Microchip" },
    { 0xF130, "Font Awesome", "Microphone" },
    { 0xF3C9, "Font Awesome", "MicrophoneAlt" },
    { 0xF539, "Font Awesome", "MicrophoneAltSlash" },
    { 0xF131, "Font Awesome", "MicrophoneSlash" },
    { 0xF068, "Font Awesome", "Minus" },
    { 0xF056, "Font Awesome", "MinusCircle" },
    { 0xF146, "Font Awesome", "MinusSquare" },
    { 0xF10B, "Font Awesome", "Mobile" },
    { 0xF3CD, "Font Awesome", "MobileAlt" },
    { 0xF0D6, "Font Awesome", "MoneyBill" },
    { 0xF3D1, "Font Awesome", "MoneyBillAlt" },
    { 0xF53A, "Font Awesome", "MoneyBillWave" },
    { 0xF53B, "Font Awesome", "MoneyBillWaveAlt" },
    { 0xF53C, "Font Awesome", "MoneyCheck" },
    { 0xF53D, "Font Awesome", "MoneyCheckAlt" },
    { 0xF5A6, "Font Awesome", "Monument" },
    { 0xF186, "Font Awesome", "Moon" },
    { 0xF5A7, "Font Awesome", "MortarPestle" },
    { 0xF21C, "Font Awesome", "Motorcycle" },
    { 0xF245, "Font Awesome", "MousePointer" },
    { 0xF001, "Font Awesome", "Music" },
    { 0xF22C, "Font Awesome", "Neuter" },
    { 0xF1EA, "Font Awesome", "Newspaper" },
    { 0xF53E, "Font Awesome", "NotEqual" },
    { 0xF481, "Font Awesome", "NotesMedical" },
    { 0xF247, "Font Awesome", "ObjectGroup" },
    { 0xF248, "Font Awesome", "ObjectUngroup" },
    { 0xF03B, "Font Awesome", "Outdent" },
    { 0xF1FC, "Font Awesome", "PaintBrush" },
    { 0xF5AA, "Font Awesome", "PaintRoller" },
    { 0xF53F, "Font Awesome", "Palette" },
    { 0xF482, "Font Awesome", "Pallet" },
    { 0xF1D8, "Font Awesome", "PaperPlane" },
    { 0xF0C6, "Font Awesome", "Paperclip" },
    { 0xF4CD, "Font Awesome", "ParachuteBox" },
    { 0xF1DD, "Font Awesome", "Paragraph" },
    { 0xF540, "Font Awesome", "Parking" },
    { 0xF5AB, "Font Awesome", "Passport" },
    { 0xF0EA, "Font Awesome", "Paste" },
    { 0xF04C, "Font Awesome", "Pause" },
    { 0xF28B, "Font Awesome", "PauseCircle" },
    { 0xF1B0, "Font Awesome", "Paw" },
    { 0xF304, "Font Awesome", "Pen" },
    { 0xF305, "Font Awesome", "PenAlt" },
    { 0xF5AC, "Font Awesome", "PenFancy" },
    { 0xF5AD, "Font Awesome", "PenNib" },
    { 0xF14B, "Font Awesome", "PenSquare" },
    { 0xF303, "Font Awesome", "PencilAlt" },
    { 0xF5AE, "Font Awesome", "PencilRuler" },
    { 0xF4CE, "Font Awesome", "PeopleCarry" },
    { 0xF295, "Font Awesome", "Percent" },
    { 0xF541, "Font Awesome", "Percentage" },
    { 0xF095, "Font Awesome", "Phone" },
    { 0xF3DD, "Font Awesome", "PhoneSlash" },
    { 0xF098, "Font Awesome", "PhoneSquare" },
    { 0xF2A0, "Font Awesome", "PhoneVolume" },
    { 0xF4D3, "Font Awesome", "PiggyBank" },
    { 0xF484, "Font Awesome", "Pills" },
    { 0xF072, "Font Awesome", "Plane" },
    { 0xF5AF, "Font Awesome", "PlaneArrival" },
    { 0xF5B0, "Font Awesome", "PlaneDeparture" },
    { 0xF04B, "Font Awesome", "Play" },
    { 0xF144, "Font Awesome", "PlayCircle" },
    { 0xF1E6, "Font Awesome", "Plug" },
    { 0xF067, "Font Awesome", "Plus" },
    { 0xF055, "Font Awesome", "PlusCircle" },
    { 0xF0FE, "Font Awesome", "PlusSquare" },
    { 0xF2CE, "Font Awesome", "Podcast" },
    { 0xF2FE, "Font Awesome", "Poo" },
    { 0xF3E0, "Font Awesome", "Portrait" },
    { 0xF154, "Font Awesome", "PoundSign" },
    { 0xF011, "Font Awesome", "PowerOff" },
    { 0xF5B1, "Font Awesome", "Prescription" },
    { 0xF485, "Font Awesome", "PrescriptionBottle" },
    { 0xF486, "Font Awesome", "PrescriptionBottleAlt" },
    { 0xF02F, "Font Awesome", "Print" },
    { 0xF487, "Font Awesome", "Procedures" },
    { 0xF542, "Font Awesome", "ProjectDiagram" },
    { 0xF12E, "Font Awesome", "PuzzlePiece" },
    { 0xF029, "Font Awesome", "Qrcode" },
    { 0xF128, "Font Awesome", "Question" },
    { 0xF059, "Font Awesome", "QuestionCircle" },
    { 0xF458, "Font Awesome", "Quidditch" },
    { 0xF10D, "Font Awesome", "QuoteLeft" },
    { 0xF10E, "Font Awesome", "QuoteRight" },
    { 0xF074, "Font Awesome", "Random" },
    { 0xF543, "Font Awesome", "Receipt" },
    { 0xF1B8, "Font Awesome", "Recycle" },
    { 0xF01E, "Font Awesome", "Redo" },
    { 0xF2F9, "Font Awesome", "RedoAlt" },
    { 0xF25D, "Font Awesome", "Registered" },
    { 0xF3E5, "Font Awesome", "Reply" },
    { 0xF122, "Font Awesome", "ReplyAll" },
    { 0xF079, "Font Awesome", "Retweet" },
    { 0xF4D6, "Font Awesome", "Ribbon" },
    { 0xF018, "Font Awesome", "Road" },
    { 0xF544, "Font Awesome", "Robot" },
    { 0xF135, "Font Awesome", "Rocket" },
    { 0xF09E, "Font Awesome", "Rss" },
    { 0xF143, "Font Awesome", "RssSquare" },
    { 0xF158, "Font Awesome", "RubleSign" },
    { 0xF545, "Font Awesome", "Ruler" },
    { 0xF546, "Font Awesome", "RulerCombined" },
    { 0xF547, "Font Awesome", "RulerHorizontal" },
    { 0xF548, "Font Awesome", "RulerVertical" },
    { 0xF156, "Font Awesome", "RupeeSign" },
    { 0xF5B3, "Font Awesome", "SadCry" },
    { 0xF5B4, "Font Awesome", "SadTear" },
    { 0xF0C7, "Font Awesome", "Save" },
    { 0xF549, "Font Awesome", "School" },
    { 0xF54A, "Font Awesome", "Screwdriver" },
    { 0xF002, "Font Awesome", "Search" },
    { 0xF010, "Font Awesome", "SearchMinus" },
    { 0xF00E, "Font Awesome", "SearchPlus" },
    { 0xF4D8, "Font Awesome", "Seedling" },
    { 0xF233, "Font Awesome", "Server" },
    { 0xF064, "Font Awesome", "Share" },
    { 0xF1E0, "Font Awesome", "ShareAlt" },
    { 0xF1E1, "Font Awesome", "ShareAltSquare" },
    { 0xF14D, "Font Awesome", "ShareSquare" },
    { 0xF20B, "Font Awesome", "ShekelSign" },
    { 0xF3ED, "Font Awesome", "ShieldAlt" },
    { 0xF21A, "Font Awesome", "Ship" },
    { 0xF48B, "Font Awesome", "ShippingFast" },
    { 0xF54B, "Font Awesome", "ShoePrints" },
    { 0xF290, "Font Awesome", "ShoppingBag" },
    { 0xF291, "Font Awesome", "ShoppingBasket" },
    { 0xF07A, "Font Awesome", "ShoppingCart" },
    { 0xF2CC, "Font Awesome", "Shower" },
    { 0xF5B6, "Font Awesome", "ShuttleVan" },
    { 0xF4D9, "Font Awesome", "Sign" },
    { 0xF2F6, "Font Awesome", "SignInAlt" },
    { 0xF2A7, "Font Awesome", "SignLanguage" },
    { 0xF2F5, "Font Awesome", "SignOutAlt" },
    { 0xF012, "Font Awesome", "Signal" },
    { 0xF5B7, "Font Awesome", "Signature" },
    { 0xF0E8, "Font Awesome", "Sitemap" },
    { 0xF54C, "Font Awesome", "Skull" },
    { 0xF1DE, "Font Awesome", "SlidersH" },
    { 0xF118, "Font Awesome", "Smile" },
    { 0xF5B8, "Font Awesome", "SmileBeam" },
    { 0xF4DA, "Font Awesome", "SmileWink" },
    { 0xF48D, "Font Awesome", "Smoking" },
    { 0xF54D, "Font Awesome", "SmokingBan" },
    { 0xF2DC, "Font Awesome", "Snowflake" },
    { 0xF5BA, "Font Awesome", "SolarPanel" },
    { 0xF0DC, "Font Awesome", "Sort" },
    { 0xF15D, "Font Awesome", "SortAlphaDown" },
    { 0xF15E, "Font Awesome", "SortAlphaUp" },
    { 0xF160, "Font Awesome", "SortAmountDown" },
    { 0xF161, "Font Awesome", "SortAmountUp" },
    { 0xF0DD, "Font Awesome", "SortDown" },
    { 0xF162, "Font Awesome", "SortNumericDown" },
    { 0xF163, "Font Awesome", "SortNumericUp" },
    { 0xF0DE, "Font Awesome", "SortUp" },
    { 0xF5BB, "Font Awesome", "Spa" },
    { 0xF197, "Font Awesome", "SpaceShuttle" },
    { 0xF110, "Font Awesome", "Spinner" },
    { 0xF5BC, "Font Awesome", "Splotch" },
    { 0xF5BD, "Font Awesome", "SprayCan" },
    { 0xF0C8, "Font Awesome", "Square" },
    { 0xF45C, "Font Awesome", "SquareFull" },
    { 0xF5BF, "Font Awesome", "Stamp" },
    { 0xF005, "Font Awesome", "Star" },
    { 0xF089, "Font Awesome", "StarHalf" },
    { 0xF5C0, "Font Awesome", "StarHalfAlt" },
    { 0xF048, "Font Awesome", "StepBackward" },
    { 0xF051, "Font Awesome", "StepForward" },
    { 0xF0F1, "Font Awesome", "Stethoscope" },
    { 0xF249, "Font Awesome", "StickyNote" },
    { 0xF04D, "Font Awesome", "Stop" },
    { 0xF28D, "Font Awesome", "StopCircle" },
    { 0xF2F2, "Font Awesome", "Stopwatch" },
    { 0xF54E, "Font Awesome", "Store" },
    { 0xF54F, "Font Awesome", "StoreAlt" },
    { 0xF550, "Font Awesome", "Stream" },
    { 0xF21D, "Font Awesome", "StreetView" },
    { 0xF0CC, "Font Awesome", "Strikethrough" },
    { 0xF551, "Font Awesome", "Stroopwafel" },
    { 0xF12C, "Font Awesome", "Subscript" },
    { 0xF239, "Font Awesome", "Subway" },
    { 0xF0F2, "Font Awesome", "Suitcase" },
    { 0xF5C1, "Font Awesome", "SuitcaseRolling" },
    { 0xF185, "Font Awesome", "Sun" },
    { 0xF12B, "Font Awesome", "Superscript" },
    { 0xF5C2, "Font Awesome", "Surprise" },
    { 0xF5C3, "Font Awesome", "Swatchbook" },
    { 0xF5C4, "Font Awesome", "Swimmer" },
    { 0xF5C5, "Font Awesome", "SwimmingPool" },
    { 0xF021, "Font Awesome", "Sync" },
    { 0xF2F1, "Font Awesome", "SyncAlt" },
    { 0xF48E, "Font Awesome", "Syringe" },
    { 0xF0CE, "Font Awesome", "Table" },
    { 0xF45D, "Font Awesome", "TableTennis" },
    { 0xF10A, "Font Awesome", "Tablet" },
    { 0xF3FA, "Font Awesome", "TabletAlt" },
    { 0xF490, "Font Awesome", "Tablets" },
    { 0xF3FD, "Font Awesome", "TachometerAlt" },
    { 0xF02B, "Font Awesome", "Tag" },
    { 0xF02C, "Font Awesome", "Tags" },
    { 0xF4DB, "Font Awesome", "Tape" },
    { 0xF0AE, "Font Awesome", "Tasks" },
    { 0xF1BA, "Font Awesome", "Taxi" },
    { 0xF120, "Font Awesome", "Terminal" },
    { 0xF034, "Font Awesome", "TextHeight" },
    { 0xF035, "Font Awesome", "TextWidth" },
    { 0xF00A, "Font Awesome", "Th" },
    { 0xF009, "Font Awesome", "ThLarge" },
    { 0xF00B, "Font Awesome", "ThList" },
    { 0xF491, "Font Awesome", "Thermometer" },
    { 0xF2CB, "Font Awesome", "ThermometerEmpty" },
    { 0xF2C7, "Font Awesome", "ThermometerFull" },
    { 0xF2C9, "Font Awesome", "ThermometerHalf" },
    { 0xF2CA, "Font Awesome", "ThermometerQuarter" },
    { 0xF2C8, "Font Awesome", "ThermometerThreeQuarters" },
    { 0xF165, "Font Awesome", "ThumbsDown" },
    { 0xF164, "Font Awesome", "ThumbsUp" },
    { 0xF08D, "Font Awesome", "Thumbtack" },
    { 0xF3FF, "Font Awesome", "TicketAlt" },
    { 0xF00D, "Font Awesome", "Times" },
    { 0xF057, "Font Awesome", "TimesCircle" },
    { 0xF043, "Font Awesome", "Tint" },
    { 0xF5C7, "Font Awesome", "TintSlash" },
    { 0xF5C8, "Font Awesome", "Tired" },
    { 0xF204, "Font Awesome", "ToggleOff" },
    { 0xF205, "Font Awesome", "ToggleOn" },
    { 0xF552, "Font Awesome", "Toolbox" },
    { 0xF5C9, "Font Awesome", "Tooth" },
    { 0xF25C, "Font Awesome", "Trademark" },
    { 0xF238, "Font Awesome", "Train" },
    { 0xF224, "Font Awesome", "Transgender" },
    { 0xF225, "Font Awesome", "TransgenderAlt" },
    { 0xF1F8, "Font Awesome", "Trash" },
    { 0xF2ED, "Font Awesome", "TrashAlt" },
    { 0xF1BB, "Font Awesome", "Tree" },
    { 0xF091, "Font Awesome", "Trophy" },
    { 0xF0D1, "Font Awesome", "Truck" },
    { 0xF4DE, "Font Awesome", "TruckLoading" },
    { 0xF4DF, "Font Awesome", "TruckMoving" },
    { 0xF553, "Font Awesome", "Tshirt" },
    { 0xF1E4, "Font Awesome", "Tty" },
    { 0xF26C, "Font Awesome", "Tv" },
    { 0xF0E9, "Font Awesome", "Umbrella" },
    { 0xF5CA, "Font Awesome", "UmbrellaBeach" },
    { 0xF0CD, "Font Awesome", "Underline" },
    { 0xF0E2, "Font Awesome", "Undo" },
    { 0xF2EA, "Font Awesome", "UndoAlt" },
    { 0xF29A, "Font Awesome", "UniversalAccess" },
    { 0xF19C, "Font Awesome", "University" },
    { 0xF127, "Font Awesome", "Unlink" },
    { 0xF09C, "Font Awesome", "Unlock" },
    { 0xF13E, "Font Awesome", "UnlockAlt" },
    { 0xF093, "Font Awesome", "Upload" },
    { 0xF007, "Font Awesome", "User" },
    { 0xF406, "Font Awesome", "UserAlt" },
    { 0xF4FA, "Font Awesome", "UserAltSlash" },
    { 0xF4FB, "Font Awesome", "UserAstronaut" },
    { 0xF4FC, "Font Awesome", "UserCheck" },
    { 0xF2BD, "Font Awesome", "UserCircle" },
    { 0xF4FD, "Font Awesome", "UserClock" },
    { 0xF4FE, "Font Awesome", "UserCog" },
    { 0xF4FF, "Font Awesome", "UserEdit" },
    { 0xF500, "Font Awesome", "UserFriends" },
    { 0xF501, "Font Awesome", "UserGraduate" },
    { 0xF502, "Font Awesome", "UserLock" },
    { 0xF0F0, "Font Awesome", "UserMd" },
    { 0xF503, "Font Awesome", "UserMinus" },
    { 0xF504, "Font Awesome", "UserNinja" },
    { 0xF234, "Font Awesome", "UserPlus" },
    { 0xF21B, "Font Awesome", "UserSecret" },
    { 0xF505, "Font Awesome", "UserShield" },
    { 0xF506, "Font Awesome", "UserSlash" },
    { 0xF507, "Font Awesome", "UserTag" },
    { 0xF508, "Font Awesome", "UserTie" },
    { 0xF235, "Font Awesome", "UserTimes" },
    { 0xF0C0, "Font Awesome", "Users" },
    { 0xF509, "Font Awesome", "UsersCog" },
    { 0xF2E5, "Font Awesome", "UtensilSpoon" },
    { 0xF2E7, "Font Awesome", "Utensils" },
    { 0xF5CB, "Font Awesome", "VectorSquare" },
    { 0xF221, "Font Awesome", "Venus" },
    { 0xF226, "Font Awesome", "VenusDouble" },
    { 0xF228, "Font Awesome", "VenusMars" },
    { 0xF492, "Font Awesome", "Vial" },
    { 0xF493, "Font Awesome", "Vials" },
    { 0xF03D, "Font Awesome", "Video" },
    { 0xF4E2, "Font Awesome", "VideoSlash" },
    { 0xF45F, "Font Awesome", "VolleyballBall" },
    { 0xF027, "Font Awesome", "VolumeDown" },
    { 0xF026, "Font Awesome", "VolumeOff" },
    { 0xF028, "Font Awesome", "VolumeUp" },
    { 0xF554, "Font Awesome", "Walking" },
    { 0xF555, "Font Awesome", "Wallet" },
    { 0xF494, "Font Awesome", "Warehouse" },
    { 0xF496, "Font Awesome", "Weight" },
    { 0xF5CD, "Font Awesome", "WeightHanging" },
    { 0xF193, "Font Awesome", "Wheelchair" },
    { 0xF1EB, "Font Awesome", "Wifi" },
    { 0xF410, "Font Awesome", "WindowClose" },
    { 0xF2D0, "Font Awesome", "WindowMaximize" },
    { 0xF2D1, "Font Awesome", "WindowMinimize" },
    { 0xF2D2, "Font Awesome", "WindowRestore" },
    { 0xF4E3, "Font Awesome", "WineGlass" },
    { 0xF5CE, "Font Awesome", "WineGlassAlt" },
    { 0xF159, "Font Awesome", "WonSign" },
    { 0xF0AD, "Font Awesome", "Wrench" },
    { 0xF497, "Font Awesome", "XRay" },
    { 0xF157, "Font Awesome", "YenSign" }
};

inline QIcon getIcon(const IconInfo *iconInfo) {
    if (iconInfo->m_font == "Material") {
        return getIcon(static_cast<MatIcon>(iconInfo->m_code));
    }  else if (iconInfo->m_font == "Font Awesome") {
        return getIcon(static_cast<MatIcon>(iconInfo->m_code));
    }
    return getIcon(static_cast<MatIcon>(iconInfo->m_code));
}
}
