 

macro( vq_platform_classes )
    foreach( CLASS ${ARGV} )
        vq_headers( ${CLASS}.h )
        if( EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${CLASS}_Common.cpp )
            vq_sources( ${CLASS}_Common.cpp )
        endif()
        if( UNIX )
            if( APPLE )
                set( SOURCE "apple/${CLASS}.cpp" )
            else()
                set( SOURCE "unix/${CLASS}.cpp" )
            endif()
        elseif( WIN32 )
            set( SOURCE "windows/${CLASS}.cpp" )
        endif()
        if( EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE} )
            vq_sources( ${SOURCE} )
        endif()
    endforeach()
endmacro()
